acdh-oeaw/apis-core-rdf

apis_core/apis_entities/filters.py

This PR re-enables filtering lists of entities by entity-specific keywords. It is implemented in a way that requires config of `list_filters` via entity models rather than via an app's settings file. Additional commits clean up existing code/formatting.
Summary of changes:
- refactor method responsible for setting filters based on `list_filter` setting in models
- move the method out of `GenericEntityListFilter`'s `__init__` method for readability
- add, improve inline code comments, Docstrings
- fix formatting issues
**Related issues and PRs**
Resolves issue:
- #16 

Resolves #16 - Re-enable list filters

---

apis_core/helper_functions/ContentType.py

The change in this PR gets rid of the Serializer-related error when adding abstract classes to models.py (see #27).
However, abstract classes continue to be displayed to users on the frontend, e.g. in the Entities dropdown in the main menu (which leads to an error when clicked, due to their non-existence). -> Any other affected views still need cleaning up as well. See also **TODO** section in the linked issue.
**Related issues and PRs**
Partially resolves issue:
- #27

Allow use of abstract classes in models.py

---

apis_core/apis_entities/views.py

This PR fixes (parts of) the problem reported and dicussed in #18 + another case of the recurring issue of `entity_settings` not getting applied to some model classes because class names aren't matched correctly.
Caveat: only `GenericListViewNew` in `apis_entities/views.py` was refactored, so other views may need equivalent work (depending on where/how `context` data is reused/set).
Summary of changes:
- Reverts `context['class_name']` to singular but _verbose_ name
- Introduces `context['class_name_plural']` for more flexibility in Django templates (once templates are refactored to work on a per-project basis, see acdh-oeaw/apis-rdf-devops#3)
- Improves ad-hoc pluralisation of class names which don't have `verbose_name_plural` set
- Fixes broken access of `entity_settings` configs for …

Fix entity names in list view + entity_settings not getting picked up

---

apis_core/apis_entities/models.py
apis_core/apis_entities/views.py

The APIS_ENTITIES are created using the values that are stored in
the `entity_settings` attribute of entities. In some cases it might
make sense to be able to define those in the global settings file.
This commit changes the code so it checks for the existense of the
APIS_ENTITIES setting and only uses the `entity_settings` attribute
if the global settings is empty.

Allow overriding the APIS_ENTITIES setting

---

apis_core/apis_relations/models.py

This PR fixes the order of variable assignments/assignment checks and unicode normalisation of strings implemented in the `save()` method of class `Property`.
Summary:
- puts `self.name_forward` assignment first for later reuse
- checks for existence of `self.name_reverse` before attempting unicode normalisation
- applies unicode normalisation to both variables
- fixes syntax
**Additional context**
Only the last commit 4e73bf9 is relevant to this PR / contains the changes described above.
All earlier commits are partial cherry-picks of PR #25 (specifically: all changes to apis_core/apis_relations/models.py), which is expected to get merged at a later point.

Fix unicode validation of Property name_forward, name_reverse 

---

apis_core/api_routers.py
apis_core/apis_entities/models.py
apis_core/helper_functions/ContentType.py

This commit introduces some try-except blocks around hardcoded imports
of `apis_ontology`. `apis_ontology` is not part of this project and
there is no dependency defined anywhere. With the exception handling
it becomes possible to run tests in this project.
Closes: https://github.com/acdh-oeaw/apis-core-rdf/issues/33

Work around hard coded dependency on apis_ontology

---

apis_core/apis_entities/models.py

This reverts commit 62565e423719a726660360cc43f72e12cdaa5520.
The commit introduced a change that broke migrations. Given that the
method is part of a model, but accesses a list of all models, this leads
to the situation that not all models are loaded yet when the model is
needed. The class will be removed anyway, so we can revert the change
for now an look for a better solution later.

Revert "apis_entities: refactor get_all_entity_classes"

---

apis_core/apis_entities/views.py

If the entity is not defined in the settings.APIS_ENTITIES dict, we use a
default of an empty dict instead of throwing an exeption.

apis_entities: use defaults if entity not in settings.APIS_ENTITIES

---

apis/urls.py

The 'webpage' django app is not part of apis. To make the apis app self
contained and not rely on a not installed thirt party app, this commit
introduces checks before including `webpage` urlpatterns.

apis: check for existence of webpage before including in urlpatterns

---

apis_core/apis_entities/templates/apis_entities/edit_generic.html

Up until now the bibsonomy events got only initialized when the document was
loaded. This led to changes in the table break bibsonomy functionality. The
bibsonomy app now moved the event initialization to a separate function, which
we now call during redrawing the table.
See also acdh-oeaw/apis-bibsonomy#15

apis_entities: Reinitialize the bibsonomy events when redrawing relation table

---

apis_core/apis_entities/forms.py
apis_core/apis_entities/models.py

The RDFParser needs the correct app_label_entities set, to find the
ContentType. We could also fix the RDFParser directly, but at the
current state this could have unknown consequences.
In the merge method of the TempEntityClass it seems that the lookup
of the ContentType also works withtout setting the app_label.

apis_entities: fix merging two entities

---

apis_core/apis_relations/models.py

The RootObject resides in apis_core.apis_metainfo and should be imported
from there. The TempEntityClass is not used in this class at all.

apis_relations: fix RootObject import and remove TempEntityClass import

---

apis_core/apis_entities/templates/apis_entities/edit_generic.html

The entity specific templates containing the merge form were dropped in
5bdeb5c as `unused legacy clutter`.

apis-entities: Readd the merge form in the edit template

---

apis_core/apis_entities/filters.py

Even if there is an unusable filter, doesn't mean the remaining
interface could not still be used. Using logging we can inform the admin
of the misconfiguration, but still show the form.

fix: use logger instead of an exception

---

apis_core/apis_entities/edit_generic.py
apis_core/apis_entities/models.py
apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html
apis_core/apis_entities/urls.py
apis_core/apis_metainfo/models.py

This commit adds a method `duplicate` to the RootObject class. The
method creates a copy of self and tries to copy some of the relations
too as well as the reverse ManyToOneRels.
The commit also introduces a `GenericEntitiesDuplicateView` in
apis_entities.edit_generic, a `get_duplicate_url` in
`apis_entities.models` and an url entry for that view. Last but not
least it adds a duplicate link to the `detail_views/detail_generic.html`
template.

feat: implement duplication of RootObject children

---

pyproject.toml

There are a couple of templates that rely on templatetags from the
acdh-django-charts project, namely in `apis_vis`:
* average.html
* inst_range.html
* avgmemperyer.html
and generic_list.html in `apis_metainfo`.

fix: add acdh-django-charts dependency

---

apis_core/apis_entities/filters.py
docs/source/configuration.rst

This commit refactors the `set_sort_filters` filters method on the
GenericEntityListFilter and renames it to `set_and_sort_filters`
It adds two now features to the APIS_ENTITIES settings dict:
In the `list_filters` list one can now define additional custom filters.
They are defined using a dict with the key being the name of the new
filter and the values being a dict containing its settings. See
https://django-filter.readthedocs.io/en/stable/ref/filters.html for
possible arguments.
In addition, we add a `list_filters_exclude` setting, which is a simple
list of string with names of filters that should be excluded. There is
the special word `__defaults__` which means that the default filters are
excluded, meaning only the filters in the `list_filters` setting will be
part of that filterset. …

feat(apis_entities): refactor code and make custom filters possible

---

apis_core/apis_metainfo/templates/browsing/generic_list.html

* Fixes how the CSS for tables from `tables.py` is included in `generic_list.html` so it actually works -> tables are supposed to have striped rows and the row being hovered over should be highlighted.
* Surrounds the table with a `div` to make it responsive -> allows horizontal scrolling of wide tables instead of cutting off columns.
**Related issues and PRs**
Resolves issues:
- #21 
- #149

Fix table rendering

---

apis_core/utils/caching.py
apis_core/utils/test_caching.py

The `get_all_contenttype_classes` method checked for abstact classes by
looking at the `_meta` attribute without checking if that `_meta`
attribute even existed. This commit adds an additional check and adds a
testcase.

fix(utils): fix bug and add test case

---

apis_core/apis_metainfo/templates/base.html

This way it sticks to its right sibling, which is currently the end of
the parent element.

fix(apis_metainfo): add zero margin to the usermenu in the navbar

---

apis_core/apis_entities/models.py

The existing for loop that should update the root_object of the Uris
sets the attribute `entity` which is not a field in the Uri model. It
simply gets lost when saving. The field is called `root_object`. We fix
this and replace the for loop with a filter update, which would have
shown the mistake in the first place.

fix(apis_entities): fix transferral of Uris in merge method

---

apis_core/apis_entities/api_views.py
apis_core/utils/utils.py

This commit lets the users define a function in an entity for providing
a custom serializer for a specific suffix. So for example, it is
possible to define a `serializer_tei` method in an entity which returns
a custom serializer which is then used if a a tei version of the api is
requested.

feat(apis_entities): let users override the serializer

---

apis_core/apis_metainfo/templates/base.html
apis_core/apis_metainfo/templates/partials/bootstrap4_css.html
apis_core/apis_metainfo/templates/partials/bootstrap4_js.html
apis_core/apis_metainfo/templates/partials/feather_js.html

This commit replaces the used `fundament` stylesheet links and script
sources with pure bootstrap4 and feather. The bootstrap stylesheet link
was put in the `partials/bootstrap4_css.html` template partial, the
needed bootstrap4 javascript sources from bootstrap and feather are in
the `partials/bootstrap4_js.html` and `partials/feather_js.html`
templates.
The stylesheet `include` was put into a `styles` block.
To make the navbar reflect the navbar as it was with fundament, the
project-logo had to be hardcoded with a height of 36px. The mr-0 we
just introduced in https://github.com/acdh-oeaw/apis-core-rdf/commit/c35d13bcf026b9946c3ec0eb908b87880a246e02, to move the usermenu to the end of the
navbar, was replaced by setting the #main-menu to `mr-auto`.
Closes: …

feat(apis_metainfo): replace fundament with pure bootstrap

---

apis/urls.py

most setups have `webpage` installed and therefore have a landing page,
but we should set a landing page nonetheless. it gets overriden if
`webpage` is installed the `webpage` urlpatterns are prepended.

fix(apis): show an empty page on `/` instead of an errorpage

---

.github/workflows/black.yml

We do now have our own repository with workflows for all the apis
repositories. This commit switches the black workflow to use that
repository.

chore: use prosnet black workflow instead

---

apis_core/apis_metainfo/templates/registration/login.html

Django by default does not come with a login template. If we want to
make APIS work out of the box at some point, we have to ship a minimal
login template. This commit introduces this template.
Closes: #210

feat(apis_metainfo): provide a login template

---

apis_core/apis_relations/templates/apis_relations/delete_button_generic_ajax_form.html
apis_core/apis_relations/templates/apis_relations/edit_button_generic_ajax_form.html

In dba667f we reformatted all templates automatically using djlint.
dlint added newlines before and after `if` statements, which leads to
broken javascript, if the `if` statement is used to generate a function
argument. This commit turns djlint off for in two places where such
arguments are created using `if` statements (the edit and delete buttons
of the relations form).
Closes: #236

fix(apis_relations): fix accidental newline after `if` in template

---

apis_core/apis_entities/edit_generic.py
apis_core/utils/helpers.py

feat: entity edit, filter related entity types to only those where a relation property exists
Currently, the relationed edit panel on the right shows all possible entities, even if no relations can actually be created between the two. This commit filters the entity types using the requested type, to limit the relatable entities to only those for which a relationship can actually be created.
This should clean up the interface quite a bit, especially where there are lots of entity types
- In the Edit view, change the right panel ("Related To") to show only the Entity types to which a relationship can actually be created (i.e. where there is a Property connecting the two entity types), rather than all entities. Implements the function …

filter allowed related types to only types where a relation-property actually exists

---

apis_core/apis_relations/models.py
apis_core/utils/caching.py

- Changed `ContentType.objects.get(model=<MODEL NAME>)` to `ContentType.objects.get_for_model(<MODEL>)`
**Additional context**
Due to case sensitivity issues in Postgres, looking up ContentTypes with the string name causes problems. Previously using the workaround script (https://github.com/acdh-oeaw/apis-ontologies/blob/8a561a50fee5220e0e93255c40cb152695531864/jelinek/ontology_specific_scripts/postgres_specific.py), but this causes further errors.
Instead, change the ContentType lookups to use the actual model, rather than the string name. There still seems to be some use of `ContentType.objects.get()` elsewhere; will investigate.

Change ContentType.objects.get to .get_for_model

---

.github/workflows/pages.yml

The workflow should ignore changes to the .github repository and only
try to push changes if there are some.

chore(docs): make documentation build workflow more robust

---

apis_core/core/mixins.py

Python does not pass the object from one parent classes' method to the
next, we have to call super() ourselves, if the method exists.
Closes: #263

fix: use the filter method of the superclass, if it exists

---

apis_core/apis_entities/detail_generic.py
apis_core/apis_entities/views.py
apis_core/apis_relations/rel_views.py

The default login_url for the UserPassesTestMixin defaults to
settings.LOGIN_URL which defaults to "/accounts/login/" - therefore the
override does not make sense.

fix(apis_entities,apis_relations): drop login_url override

---

apis_core/apis_relations/forms2.py
apis_core/apis_relations/tables.py
apis_core/apis_relations/views.py

The TempTriple model has a notes field, that should be usabel to store
metadata. This commit adds it to the form and the form handling of the
GenericTripleForm.
Closes: #197

fix(apis_relations): show notes field and store notes

---

apis_core/apis_relations/tables.py

There are projects that use references on relations. Therefore the
references button should also be listed in the reference table - this is
already the case in the edit view, but not yet in the detail view. This
commit hardcodes this button in the detail view. This is a hack, but
given that the whole Reference logic is rewritten, it does not make much
sense to refactor the whole codebase to make this table more
customizable.

fix: show reference button in detail view

---

apis_core/core/models.py

This commit introduces a LegacyDateMixin that provides commonly used
fields for models that need a temporal component. This is based on
relations and entities as they were used in APIS until now.
Closes: #66

Introduce TimespanMixins

---

apis_core/apis_metainfo/templates/base.html

The menu block contained a default `About` menu item, allowing the user
to add custom menu items. By default, that menu item is emtpy, so it
showed a dropdown menu without any menuitems.
This commit replaces this menu item with a `main-menu-extra` block. This
gives downstream projects more control over the menu, letting them add
not only menu items to an existing menu, but also additional menus.
The block around the existing dropdown menus was renamed: prior to this
it was called `custom_dropdown_menus` which is a bit misleading, given
it contains the default apis menu items. This block was renamed to
`main-menu` (like the id of the `ul` tag it is enclosed in).

feat(apis_metainfo): cleanup menu block in base template

---

apis_core/apis_entities/templates/apis_entities/edit_generic.html

This makes it easier to override the relations forms. The same approach
is also used in the `detail_generic.html` template.

feat(apis_entities): the relations listing in a relations block

---

apis_core/apis_metainfo/templates/base.html

This commit encloses the user menu in the base template in a
`userlogin-menu` block. This lets downstream projects override the
userlogin-menu without having to copy the whole template (like
apis-webpage did until now).
This commit also removes the `Use edit views` checkbox, because it had
no effect. The commit also adds a closing `</div>` that was missing
before, thats why the whole structure after the change got reindented.

feat(core): add userlogin-menu block to `base.html`

---

pyproject.toml

Support everything greater than or equal to 3.11.
This makes the project more compatible with other Python projects.
Closes: #255

fix(deps): loosen Python dependency

---

apis_core/apis_entities/api_mappings/cidoc_mapping.py
apis_core/apis_vocabularies/api_renderers.py

This way the application doesn't crash and burn when PROJECT_DEFAULT_MD
is not set.

fix: use empty dict as fallback for PROJECT_DEFAULT_MD

---

apis_core/apis_relations/forms2.py

where an entity might have more than one URI
primary URI is one that is in the same domain as
defined in APIS_BASE_URI in settings
the default value for APIS_BASE_URI is hardcoded to be consistent with the same value used in apis_entities at the time of the creation of the URI object
Resolves issue:
- #221 
- [x ] My changes don't generate new warnings or errors
- [x ] My changes follow the project's code formatting rules and style guidelines

Consider only the first primary URI of entities

---

apis_core/core/models.py

The LegacyDateMixin uses datefields, but the DateParser returns
datetimes. Therefore we have to get the dates from the returned values.
Closes: #295

fix: LegacyDateMixin get dates from DateParser datetimes

---

apis_core/api_routers.py
docs/source/configuration.rst

The API does not allow the entity id to be writeable by default. This
commit introduces a setting that lets the user override this behaviour.
Closes: #296

fix(api_routers): allow to let the `id` field be writeable in API

---

apis_core/apis_entities/forms.py

There is some legacy code that expects specific model fields (the ones
that were part of TempEntityClass). This commit checks if those even
exist, before setting their attributes.
Closes: #298

fix(apis_entities): only set field attributes for existing fields

---

apis_core/api_routers.py

Those are interfering if there is a `Text` model defined in a project

fix: get rid of text model remains

---

apis_core/apis_entities/forms.py

`collection` is a leftover of the TempEntityClass. some projects still
use that, so we set it if it exists, but we check first if the object we
are working with even has such an attribute.
Closes: #313

fix(apis_entities): only set collection if the attribute exists

---

apis_core/apis_entities/templatetags/apis_templatetags.py
apis_core/apis_metainfo/templates/base.html
apis_core/core/templatetags/apiscore.py

This commit introduces a core templatetag `shared_url` to access the
`SHARED_URL` setting (the templatetag defaults to `/static/`). It also
updates the base template to use this templatetag.
The commit also introduces an apis_entities templatetag
`entities_list_links` that returns a list of links to the list views of
all entities. It also updates the base template to use this templatetag.
Closes: #293

feat: introduce new templatetags

---

apis_core/apis_entities/templates/apis_entities/apis_templatetag.html

This way our custom function is still called, even if the function call
above it fails - which it does, if the apScrollTop thingy is not
installed.

fix: put function call in separate document.ready function

---

apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html

The `references` of an entity were listed two times in the detail view.
This commit removes the second occurence. Somehow this leads to djlint
being confused, therefore an unrelated newline has to be remove too...

fix: remove duplicate of `references` attribute in detail view

---

apis_core/apis_entities/autocomplete3.py
apis_core/apis_entities/filters.py
apis_core/apis_entities/forms.py
apis_core/apis_entities/views.py

This replaces every occurence of direct access to settings.APIS_ENTITIES
with the helper function `get_entity_settings_by_modelname`

refactor: use `utils.settings.get_entity_settings_by_modelname`

---

apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html

The relations were a card in a card in a card. Thats too much borders
and clutters the view. Lets at least drop the most inner card.

refactor(apis_entities): cleanup relation listings in detailview

---

apis_core/apis_entities/detail_generic.py
apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html

The approach so far was to manually go through all the fields and have
an `exclude` list. It makes more sense to use `model_to_dict` from
django forms. If projects need more customization, they can override the
template.
The variable was also renamed to `relevant_fields` and we also pass the
field to the template, to be able to access the verbose_name.
Closes: #331

refactor(apis_entities): rewrite the relevant fields logic

---

apis_core/apis_metainfo/templates/base.html

The relations list was sourced from a context processor. This is
overengineered for a list of two items. We therefore replace the items
with a hardcoded list, which allows us to drop the context processor in
the future.

refactor: replace the `relations_list` with hardcoded links

---

apis_core/apis_entities/tables.py
apis_core/apis_entities/views.py
apis_core/utils/settings.py

When this variable is set, the entity list views link to the edit views
of the individual entities.
The former `edit_v` session variable was removed.

fix: introduce APIS_LIST_LINKS_TO_EDIT variable

---

apis_core/apis_entities/models.py

refactor!: move methods from TempEntityClass to AbstractEntity

---

apis_core/apis_entities/filters.py

`collections` is a field from TempEntityClass - it does not have to be
hardcoded in the filter. If it exists in the model, the filter will show
it anyway.
Closes: #354

fix: drop `collections` as default field from entities filter

---

apis_core/apis_entities/detail_generic.py
docs/source/configuration.rst

This excludes fields that are part of TempEntityClass - in the long run,
this can be removed. But given that there are still projects using
TempEntityClass, this is a temporary workaround

fix: readd exclude list of fields in detail view

---

apis_core/apis_metainfo/templates/base.html

This allows to override them in projects

fix: put footer and imprint in separate template blocks

---

apis_core/apis_entities/detail_generic.py

This gives us a more meaningful represeantaion of the value

fix: use value from model_to_dict instead of getattr

---

apis_core/apis_metainfo/templates/base.html

We only include the stylesheet if the variable is set - otherwise we
always have two hits to the page itself.
Closes: #364

fix: surround embedding of custom stylesheet with if statement

---

apis_core/apis_entities/models.py

It is not used anywhere and it uses `get_child_entity` which was
apparently already dropped during
c60e6df4d53918dea6ed2be5b2d2225eb8fde894
Closes: #323

fix: drop `get_child_class()` from AbstractEntity

---

apis_core/apis_entities/serializers_generic.py

We are moving away from expecting fields in our entities, therefore it
makes sense to make the EntitySerializer a bit more flexible. By default
it serializes all the fields of the entity anyway - so we can simply
remove `name`, `start_date` and `end_date` in this case. The `label_set`
is a leftover of the legacy setup with TempEntityClass, we no check for
its existence before adding the field.
Closes: #383

fix: do not expect fields in EntitySerializer

---

apis_core/apis_entities/api_views.py

TempEntityClass will be dropped at some point, so we change the
serializer to use the RootObject instead
Closes: #380

fix: use RootObject instead of TempEntityClass in GetEntityGeneric

---

apis_core/apis_entities/edit_generic.py

The variable is passed to the template via the context but not used
anywhere and it creates problems with ontologies not using reversion.
Therefore we drop the variable.
Closes: #407

fix: drop object_revisions from generic entities edit view

---

apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html

The detail template references a couple of attributes that can not be
expected of entities anymore. In addition, due to the reimplementation
of the `relevant_fields` logic in 13986b8 the template does not have to
list attributes manually. Therefore we remove some attributes from the
listing and others are now surrounded by {% if %}{% endif %} statements.
Closes: #396

fix: cleanup entities detail template

---

apis_core/apis_entities/tables.py

The error message which can appear when trying to load entity list views has become outdated (makes references to entity settings declarations we don't use anymore), this PR fixes this + rewords the message for clarity.

fix: rewrite error message

---

apis_core/context_processors/webpage_content_processors.py

Its not used anywhere in the codebase since
0ce7df4e34efc31b5b3c80374b70889ffbe7938e

refactor: drop webpage_content_processors

---

README.md
apis_core/context_processors/custom_context_processors.py
tests/settings_ci.py

We don't need them anymore since
0ce7df4e34efc31b5b3c80374b70889ffbe7938e and
51a0e5d42ab7651c3013793adb17949fa9debcb6

fix: drop unused custom context processors

---

apis_core/core/management/commands/apisdumpdata.py
apis_core/core/views.py
apis_core/urls.py
apis_core/utils/helpers.py

This feature provides ways to serialize the data of an APIS instance to
be able to import it in a freshly installed instance later on.
The main logic is implemented in the `utils.helper.datadump_serializer`
method. It serializes the important models to json - with natural
foreign keys.
There is both a view ('/apisdumpdata.json') and an admin command
('apisdumpdata') that output the serialized data as HttpResponse or to
stdout.
Closes: https://github.com/acdh-oeaw/apis-core-rdf/issues/273

feat: implement dumpdata view

---

apis_core/apis_entities/forms.py

`meta_fields` were a concept of `TempEntityClass`, which is being phased
out
Closes: #475

fix: drop meta_fields from forms

---

apis_core/apis_entities/edit_generic.py
apis_core/apis_entities/templates/apis_entities/edit_generic.html

This replaces some context data with attributes from the instance, it
removes any label specific code and drops some imports that were not
used.

refactor: cleanup `apis_entities.edit_generic` + template

---

README.md
poetry.lock
pyproject.toml

BREAKING CHANGE: django-crispy-forms uses separate template packs since
version 2. we depend on crispy-bootstrap4 by default, but projects have
to add `crispy_bootstrap4` to the INSTALLED_APPS themselves.

chore(deps): add crispy-bootstrap4 as dependency

---

apis_core/apis_entities/models.py
apis_core/apis_vocabularies/models.py
apis_core/apis_vocabularies/serializers.py
apis_core/utils/test_caching.py

Given that we don't use the `Label` model anymore since
0c44287eac678f40a24c98ffe8b7efb053487db4, we can safely remove
`LabelType`, too
Closes: #498

refactor!: drop `apis_vocabularies.models.LabelType`

---

apis_core/apis_entities/edit_generic.py
apis_core/apis_entities/forms.py
apis_core/apis_vocabularies/models.py
apis_core/apis_vocabularies/serializers.py
apis_core/utils/test_caching.py

Given that we removed `Text` in 063412fb28bb812325010bae333f19ea3cb7bd8d
we don't need `TextType` anymore either.
Closes: #499

refactor!: drop `apis_vocabularies.models.TextType`

---

apis_core/apis_entities/detail_generic.py
apis_core/apis_entities/edit_generic.py
apis_core/utils/helpers.py

This commit moves duplicated triple generation code that resided in both
the entities edit view and the entities detail view to the helpers
module so it can be reused by both views.
Closes: #480

refactor: move duplicated triple code to `apis_core.utils.helpers`

---

apis_core/generic/api_views.py
apis_core/generic/filtersets.py
apis_core/generic/forms.py
apis_core/generic/helpers.py
apis_core/generic/serializers.py
apis_core/generic/tables.py
apis_core/generic/templates/columns/delete.html
apis_core/generic/templates/columns/description.html
apis_core/generic/templates/columns/edit.html
apis_core/generic/templates/columns/view.html
apis_core/generic/templates/generic/generic_confirm_delete.html
apis_core/generic/templates/generic/generic_content.html
apis_core/generic/templates/generic/generic_detail.html
apis_core/generic/templates/generic/generic_form.html
apis_core/generic/templates/generic/generic_list.html
apis_core/generic/templates/generic/overview.html
apis_core/generic/templatetags/apisgeneric.py
apis_core/generic/urls.py
apis_core/generic/views.py
apis_core/urls.py
tests/settings_ci.py

This commit introduces a `generic` app, that provides generic Create,
View, Update, Delete, List and Autocomplete views that work with
ContentTypes as well as an API viewset that also works with ContentTypes
Most of the used classes (Table, FilterSet, Serializers, ...) can be
overriden an every level of the inheritance chain.
Closes: #509

feat: introduce generic app

---

apis_core/apis_relations/tables.py

Switch from class name to verbose name, capitalise strings instead of title-casing them

refactor: use model verbose names in property table

---

.github/workflows/gitlint.yml

dependabot uses longer lines sometimes

ci: allow longer lines in git commit messages

---

apis_core/apis_metainfo/models.py

The get_or_create method calls the get method, so it makes sense to put
the url cleaning in the get method itself.

refactor(apis_metainfo): move clean_uri from get_or_create to get

---

apis_core/generic/views.py

This extens the `generic.views.Autocomplete` endpoint to allow adding
custom results to the autocomplete answer. It also adds an option to
*only* return custom results and not the defaults.

feat(generic): allow to extend autocomplete results with custom results

---

apis_core/apis_metainfo/serializers.py

The TextSerializer is not being used anymore, given that there are no
texts in apis-core. The UriSerializer now inherits from the
GenericHyperlinkedModelSerializer, that way it can resolve all the links
to api endpoints to foreign keys.

fix: drop TextSerializer and use GenericHyperlinkedModelSerializer

---

apis_core/generic/helpers.py
apis_core/generic/tables.py
apis_core/generic/views.py

This introduces a wrapper `generic.helpers.permission_fullname` to
create the fullname of a permission based on the action and the model.
This is then used in the table class to hide columns that are not
can not use, due to missing permissions.
The wrapper is now also used in the views.GenericModelMixin.
Closes: #584

fix: only show table actions if user has required permissions

---

apis_core/apis_entities/autocomplete3.py

This is just a temporaray workaround, because this autocomplete3 module
is still used for the relations forms.

fix: add more information to autocomplete results

---

apis_core/api_routers.py

`metadata` is a JSONField, which leads to errors - we have to fix. This
is a hardcoded variable, but we have to throw away that whole
api_routers stuff anyway.

fix: exclude `metadata` field from legacy api viewset stuff

---

apis_core/generic/forms/fields.py
apis_core/generic/views.py
apis_core/utils/helpers.py

This commit moves the logic of creating a model instance from an URI to
`apis_core.utils.helpers.create_object_from_uri`. This way it can be
reused - and this is exactly what we do in the
`apis_core.generic.views.Autocomplete` view. This view can now create
objects by receiving a POST with a value - it uses
`create_object_from_uri` to do this.
The ModelImportChoiceField now also uses this method to create the
object.

fix: let the autocomplete form create objects

---

.github/workflows/add-to-project.yml

I'm actually not _entirely_ sure if GitHub really differentiates between strings and numbers in action variables, so left the `PROJECT_NUM` setting as-is and set the `GH_PROJECT_NUM` var. :eyes:

Add add-to-project.yml workflow based on prosnet-workflows template

---

apis_core/generic/templatetags/apisgeneric.py

The `modeldict` method tries to "do the right thing" when it comes to
displaying attribute values of models. When there is a foreign key, the
method should replace the ID with the value of the model instance it
points to.

feat(generic): display foreign key fields as value instead of id

---

apis_core/collections/templates/collections/collection_object_parent.html
apis_core/collections/templates/collections/collection_toggle.html

That way we can style using css files without overriding the whole
template.
Closes: #604

feat: add collection name as css class to collection templates

---

apis_core/apis_entities/rdfimport/InstitutionFromDNB.toml
apis_core/apis_entities/rdfimport/PersonFromDNB.toml
apis_core/apis_entities/rdfimport/PlaceFromDNB.toml
apis_core/apis_entities/rdfimport/PlaceFromGeonames.toml
apis_core/apis_metainfo/models.py
apis_core/utils/rdf.py
apis_core/utils/settings.py
apis_core/utils/test_rdf.py

The sparql files now reside in `apis_entities/rdfimport` and the list of
sparqlfiles can be extended, resp. the existing ones overridden, by
putting `.toml` files in any `rdfimport` folder of a Djang app.
The function for parsing the RDF endpoint was renamed to
`get_defintion_and_attributes_from_uri`. Given the new logic to iterate
through the app `rdfimport` folders, it does not use the
`APIS_RDF_YAML_SETTINGS` setting anymore, which was therefore dropped
(together with the corresponding function from `utils.settins`)
Closes: #603

refactor(utils): split up rdf import sparqlfiles and move them

---

apis_core/generic/tables.py

The DeleteColumn, EditColumn and ViewColumn only differ in their
template, so we combine their attributes into an ActionColumn and only
set the template name in the children classes.

refactor(generic): create an ActionColumn to combine similar attributes

---

apis_core/apis_metainfo/models.py

This is used to signal that this method does not only return a value,
but does indeed modify data (in this case create new model instances).

fix(apis_metainfo): set the `alters_data` attribute of duplicate

---

apis_core/generic/views.py
docs/source/customization.rst

The Select2QuerySetView can use a template to render autocomplete
results. We use the `get_template_names` method to find a list of
possible template names and if `select_template` finds a valid one, we
use that to render the autocomplete results.

feat(generic): use template attribute of autocomplete view

---

apis_core/apis_relations/forms.py

The form for editing relations loads the form and sets the
`other_entity` value to the URI of the other entity. For that it checked
if the URI startswith APIS_BASE_URI - which does not work if the
APIS_BASE_URI is not set. But it doesn't make any sense to make that
`startwith` check. Any URI in the list of URIs should work.

fix: don't rely on APIS_BASE_URI for editing relations

---

apis_core/apis_entities/tables.py

If the user does not have the `create` permission, which is required to
duplicate an entity, we hide the button.

fix(apis_entities): hide duplicate button on missing permission

---

apis_core/generic/helpers.py

feat(generic): use lru cache for smaller methods

---

apis_core/utils/autocomplete.py

Those ExternalAutocomplete and ExternalAutocompleteAdapter classes
can be used to build upon when implementing external autocomplete
queries.
Closes: #653

feat(utils): provide some abstract base classes for autocomplete

---

apis_core/core/templates/base.html
apis_core/generic/templates/generic/generic_list.html

This setting allows htmx to act on responses that are empty, like the
ones it gets when it sends a DELETE to the API. That is something we
want to use in multiple places in APIS, not only in the generic app.

fix(generic,core): move htmx setup from generic template to base.html

---

apis_core/apis_entities/abc.py
apis_core/core/abc.py

feat(apis_entities): implement default entity classes

---

apis_core/apis_entities/templates/apis_entities/partials/entity_actions_nav.html
apis_core/apis_entities/templates/apis_entities/partials/entity_base_nav.html

In the actions templates we used `verbose_name` to create the urls that
point to the entity views - but the `verbose_name` is more meant as a
presentation string, than part of an URI. We use the modelname now
instead.

fix(apis_entities): use `modelname` instead of `verbose_name`

---

apis_core/apis_entities/models.py
apis_core/apis_metainfo/models.py
apis_core/apis_metainfo/test_models.py

The `RootObject` and the `AbstractEntity` models had an override for the
`__str__` method, that referenced the models `.name` field. We are
planning on removing the `.name` field and the `__str__` methods should
be implemented in child classes anyway, so this commit removes the
overrides from `RootObject` and `AbstractEntity`
It also deletes the test, as we are now using Django's default
behaviour.
cherry picked from apis-core-rdf#630 by birger

refactor(apis_metainfo,apis_entities)!: drop __str___ overrides

---

apis_core/apis_entities/filtersets.py
apis_core/apis_relations/forms.py
apis_core/apis_relations/management/commands/create_relationships.py
apis_core/apis_relations/models.py
apis_core/apis_relations/tables.py
apis_core/utils/caching.py
apis_core/utils/filtermethods.py

This commit replaces all references to `Property.name` with
`Property.name_forward`, because `.name` will be removed in the near
future.
cherry picked from apis-core-rdf#630 by birger

refactor(apis_relations): use name_forward for property where applicable

---

apis_core/utils/rdf.py

The check was designed to check the type of the passed object is a
sublcass of the superclass, but we usually pass a class and not an
instance, so lets also check the class itself.

fix(utils): make rdfimport parent model check more loose

---

apis_core/apis_entities/models.py
apis_core/apis_entities/templates/apis_entities/partials/entity_base_nav.html
apis_core/apis_metainfo/models.py
apis_core/generic/abc.py
apis_core/generic/views.py

We ship generic views with the generic app and those views are activated
for a model that inherits from GenericModel. Therefore we can now also
add methods to GenericModel that return canonical urls for those views.

refactor(generic): move url methods to GenericModel

---

apis_core/core/templates/base.html

The base template still contained a couple of references to variables
that stem from the webpage context processors. We don't use those
anymore, so lets get rid of those variables, to make the templates more
readable.
Closes: #410

chore(core): drop webpage remains from template

---

apis_core/apis_metainfo/models.py

The ContentType framework already provides a built in caching mechanism
of contenttypes, therefore we don't need a custom solution.

fix(apis_metainfo): use ContentType instead of custom caching

---

apis_core/generic/serializers.py

This serializer can be used by API endpoints to retreive a model
instance by natural key and id.

feat(generic): add ContentTypeInstanceSerializer

---

apis_core/apis_relations/tables.py

This way we use the same order of fields as in the other tables
inheriting from GenericTable.
Closes: #716

fix(apis_relations): reuse GenericTable.Meta.sequence for tables

---

apis_core/apis_entities/abc.py
apis_core/core/abc.py

We decided to drop the label for the E21_Person model, because it has a
forename and a surname. Because there are now only two BaseModels left
that use the LabelBaseModel, we moved the label field directly in those
models and dropped the LabelBaseModel

refactor(apis_entities): drop core.abc.LabelBaseModel

---

apis_core/apis_relations/filtersets.py

This filter allows us to filter Properties by the contenttype of the
subj and the obj and we can reuse it in the TripleFilterSet for the
subj_class and obj_class filters.

feat(apis_relations): add and use PropertySubjObjFilter

---

apis_core/generic/generators.py

The CustomSchemaGenerator is meant as a drop in replacement for the
"DEFAULT_GENERATOR_CLASS" of drf-spectacular. You can use it like this:
SPECTACULAR_SETTINGS["DEFAULT_GENERATOR_CLASS"] = 'apis_core.generic.generators.CustomSchemaGenerator'
Reasons:
The first reason is, that we are using a custom converter
(`apis_core.generic.urls.ContenttypeConverter`) to provide access to views
and api views of different contenttypes. The default endpoint generator of
does not know about this converter and therefore sees the endpoints using
this converter as *one* endpoint with one parameter called `contenttype`.
Thats not what we want, so we have to do our own enumeration - we iterate
through all contenttypes that inherit from `GenericModel` and create
schema endpoints for those programatically.
The …

feat(generic): implement custom schema generator

---

apis_core/core/templates/partials/bootstrap4_css.html

please note: this is a preliminary fix and should be removed when moving to bootstrap5, see the comments in the corresponding issue
resolves #330

fix: fix css for select2 autocompletes

---

apis_core/apis_relations/models.py

- Set default value for missing name_reverse field before attempting unicode normalisation
- Run unicode normalisation on string representations of the two name fields

fix(relations): Property fields unicode normalization

---

apis_core/generic/forms/__init__.py

The generic form overrides the default select widgets with autocomplete
widgets provided by the django autocomplete light app. This can only
work for contenttypes that provide an autocomplete endpoint. We can only
be sure of that for models that inherit from the GenericModel, so we
skip the override for all the others.
Closes: #764

fix(generic): use dal widget only for models with autocomplete endpoint

---

apis_core/core/templatetags/apiscore.py

This filter allows to access a models Meta options
(https://docs.djangoproject.com/en/5.0/ref/models/options/) in a
template via a ContentType object.

fix(core): add a model_meta templatetag filter

---

apis_core/apis_entities/templatetags/apis_templatetags.py
apis_core/core/templates/base.html

A new `entities_content_types` templatetag is being introduces, which
lists all content types that inherit from `AbstractEntity`. This is now
being used in the base template to get a list of entities for the
entities menu item.

refactor(apis_entities): use verbose_name_plural in the entity list menu

---

apis_core/history/models.py
apis_core/history/templatetags/apis_history_templatetags.py

This way we don't have to parse the timestamp
Closes: #784

fix(history): sort history data directly in model, not in templatetag

---

apis_core/history/views.py

The `convert_timestamps` function is not used anymore since ace42ef
The `create_new_version` view contained code thats not being used.

refactor(history): remove unused code

---

apis_core/history/models.py

The historical models use `history_id` as id instead of the `id` of the
instance they refer to. We therefore override the `get_absolute_url`
method, so that it points to the historical record and not to the
instance it refers to.

fix(history): add a get_absolute_url method to APISHistoryTableBase

---

apis_core/history/apps.py
apis_core/history/models.py
apis_core/history/signals.py

When doing a CASCADING delete, the `delete` method of an instance is not
called, but the `pre_delete` signal is triggered. We want to set the
current date for the `_history_date` attribute, if it is None. To do
that also in cascading deletes, we use the pre_delete signal.
Closes: #814

fix(history): use signal instead of method for setting timestamp

---

apis_core/history/apps.py
apis_core/history/models.py
apis_core/history/signals.py

Setting the history_date fallback directly in the property lets us drop
the `save()` override and the `pre_delete` signal, because those only
implemented a check if the history_date was None.

fix(history): implement history_date fallback directly in property

---

apis_core/generic/abc.py
apis_core/generic/views.py

This way they can be overridden by the inheriting object.
The create_success_url now points to the absolute_url of the instance.
Closes: #834

feat(generic): introduce success_url getters for create and update

---

manage.py
sample_project/settings.py

The `./manage.py` script still contained a fix that was superseeded by
using `apis-override-select2js` long ago, sow we drop that fix.
Additionaly, we point DJANGO_SETTINGS_MODULE to `sample_project`, which
was still pointing to `apis` which was dropped. And we format the whole
file to look more similar to the default Django generated `manage.py`.
The `sample_project/settings.py` now drops the hardcoded secret key and
regenerates one every execution (or uses one from the environment). We
also removed some unused apps from INSTALLED_APPS and unused entries
from MIDDLEWARE and TEMPLATES.

chore(sample_project): cleanup ./manage.py and settings.py

---

apis_core/apis_entities/templatetags/apis_templatetags.py
apis_core/core/templates/base.html

This introduces `entities_verbose_name_plural_listview_url` templatetag,
which returns all entities verbose names together with their list uri,
sorted in alphabetical order.
This is then used in the core template for the main entities menu.
Closes: #860

fix(apis_entities,core): add templatetag for generating entitymenu

---

.github/workflows/pages.yml

We don't need a specific python version, we don't need to specify a
clone folder or the branch, we don't need to overconfigure poetry ...

refactor(ci): cleanup documentation generation workflow

---

apis_core/apis_entities/views.py
apis_core/apis_relations/models.py
apis_core/utils/utils.py

These print statements look like they are leftovers from testing/debugging things during local development and could/should thus be cleaned up.

refactor: remove leftover print statements

---

apis_core/apis_entities/urls.py

In rare cases (i.e. when you remove a model and don't cleanup the
ContentTypes) we end up having ContentTypes in Djangos DB that have
None as a `model_class`. But we can not check if None is a subclass, so
we have to remove those instance before doing the check.

fix(apis_entities): remove None values before checking model_class

---

apis_core/apis_metainfo/models.py

In `duplicate`, return the actual duplicated object and pass it into the `post_duplicate` signal (instead of using the result of the object save(), which returns None).
Closes: #889

fix(apis_metainfo): fix object duplication

---

Dockerfile
sample_project/entrypoint.sh
sample_project/management/commands/setup.py

feat: add Docker image + sample_project entrypoint & setup

---

apis_core/apis_entities/autocomplete3.py
apis_core/apis_relations/forms.py
apis_core/apis_relations/views.py

`get_object_or_404` errors if we are filtering for the modelname only
(before, we filtered for modelname in the `apis_ontology` app). When we
work with models that have the same name as models in Django (like
`Group`) this leads to multiple results, which `get_object_or_404` does
not like. Therefore we are now first making a list of contenttypes that
are entities, then we filter for the model name, then we pick the first
one.
This whole nonsense will be replaced anyway, when we implement new
relations...

fix(apis_relations,apis_entities): replace get_object_or_404

---

apis_core/utils/helpers.py

The entities types a relation can point to can be changed at any time,
so they should not be cached.
Closes: #914

fix(core): don't cache the possible relation entities

---

apis_core/apis_entities/autocomplete3.py
apis_core/apis_entities/urls.py

The class hardcodes entity types and an applabel prefix. Even if thats
fixed, id does not work (`reduce() of empty iterable`). The class is
not implemented in a readable way. Lets just throw it away and
reimplement it if we need it somewhere in the future...

refactor(apis_entities)!: drop GenericNetworkEntitiesAutocomplete

---

apis_core/apis_entities/autocomplete3.py
apis_core/apis_relations/forms.py
apis_core/apis_relations/views.py

Modelnames are sometimes with an uppercase first letter, so lets lower
that string before comparing with the `.model` attribute of the
contenttype.

fix(apis_relations, apis_entities): use `lower` when comparing modelname

---

apis_core/apis_entities/templates/apis_core/apis_entities/abstractentity_form.html
apis_core/apis_relations/tables.py
apis_core/apis_relations/templates/apis_relations/delete_button_generic_ajax_form.html

This has the advantage of providing the same `delete` button for
relations as we have in other tables (with htmx and html fallback). We
can thus drop the older delete javascript functionality.

refactor(apis_relation): use GenericTable as TripleTableBase base

---

apis_core/apis_entities/models.py

This changes the `create_default_uri` signal receiver to check if there
is a `skip_default_uri` attribute of the instance and skips the creation
if that attribute is set to True.
Closes: #436

fix(apis_entities): allow to skip default uri creation

---

apis_core/generic/tables.py

The context is only added if we user `render_table` in a template - but
the some tables are rendered directly to html, circumventing the
`render_table` method, which leads to them missing the `context`.
The `request` itself though can be passed to the table directly.

fix(generic): use request intead of context for checking user

---

apis_core/apis_entities/templates/apis_core/apis_entities/abstractentity_form.html
apis_core/apis_entities/views.py
apis_core/apis_metainfo/serializers.py
apis_core/apis_metainfo/templates/registration/login.html
apis_core/apis_metainfo/viewsets.py
apis_core/apis_relations/forms.py
apis_core/apis_relations/tables.py
apis_core/apis_relations/templates/apis_relations/_ajax_form.html
apis_core/apis_relations/templates/apis_relations/_ajax_form_generic.html
apis_core/core/templates/base.html
apis_core/generic/views.py

fix: drop `apis` namespace for all url resolvers

---

sample_project/entrypoint.sh
sample_project/settings_loaddata.py

resolves #915
In the fixtures m2m fields are populated directly when the object is created. Given that we activate the tracking of m2m fields by default in simple_history loaddata creates not null constraints errors for objects that have m2m relations. Also the history is anyway in the fixtures, so no need to activate the plugin during import of the data.

fix: deactivate simple_history plugin for loaddata

---

.github/workflows/release-please.yml

Update link to release-please GitHub action after
Google moved repos/archived the last known repository.

ci(workflows): update link to release-please-action

---

apis_core/apis_entities/templatetags/apis_templatetags.py
apis_core/history/templatetags/apis_history_templatetags.py
apis_core/history/utils.py
apis_core/utils/helpers.py

The `get_classes_with_allowed_relation_from` method created a list of
possible related models based on the name of one model. It then returned
the names of those models as strings. It makes more sense to simply use
contenttypes instead of model names, especially since the Property model
stores the possible subj and obj classes as ContentTypes.
This commit refactors the method and also updates `triple_sidebar` which
is the only funciton that uses the
`get_classes_with_allowed_relation_from` method.
Closes: #254

refactor(utils): use contenttype instead of model name for helper

---

README.md

Now that the hardcoded `apis_ontology` name got dropped, we can remove
this constraint also from the installation instructions.

fix(readme): clean up installation instructions

---

apis_core/apis_vocabularies/migrations/0001_initial.py
apis_core/apis_vocabularies/migrations/0002_remove_texttype_collections_and_more.py

`apis_metainfo.Collection` was removed, so we remove everything pointing
to that model from the migrations.

fix(apis_vocabularies): remove collections from migrations

---

apis_core/apis_metainfo/tables.py
apis_core/apis_relations/tables.py

The `order_` methods are only being used by the TripleBase table, so it
make sense to move them into the table. Doing that we also refactor the
method itself.

refactor(apis_relations): move order methods into table

---

apis_core/apis_relations/tables.py

The LinkColumn has been deprecated by the django-tables2 project, we
should therefore replace it with Column and the `linkify` keyword. This
also lets us use the `get_absolute_url` resp. `get_edit_url` methods of
the entities.
Closes: #676

fix(apis_relations): replace LinkColumn with Column in TripleTables

---

apis_core/generic/templates/generic/overview.html
apis_core/generic/templatetags/apisgeneric.py

This commit introduces the templatetag `genericmodel_content_types`
which lists all content types of models that inherit from
`apis_core.generic.abc.GenericModel`. This templatetag is then used
in the overview template to create an overview of *all* those
contenttypes and not only `apis_ontology` and `collections` as it was
hardcoded beofre.
Closes: #912

feat(generic): list all generic models on overview page

---

apis_core/apis_metainfo/models.py

Up until now we hardcoded handling the `id` field, which ususally is a
primary key. Now the duplicate method handles all the unique fields and
removes them before duplicating.

fix(apis_metainfo): handle unique fields in the duplication logic

---

apis_core/apis_entities/filtersets.py

The filter `related_properties` listed all the existing properties, but
it makes more sense to only list the properties that can have the model
the filter filters as a `subj` or an `obj`.
Closes: #949

fix(apis_entities): only list possible properties in filterset form

---

apis_core/generic/api_views.py
apis_core/generic/helpers.py
apis_core/generic/renderers.py

**feat(generic): allow apiview to use custom serializers & renderers**
The commit configures the generic API view to look for more differently
configured serializers. The serializers can now also be prefixed with
the requested format, as configured in the renderer.
**feat(generic): ship generic RDF renderers**
They can be enabled as described in the upstream DRF framework
documentation:
https://www.django-rest-framework.org/api-guide/renderers/#setting-the-renderers
They expect the renderer to put triples in the data object and they
build the graph based on these triples.
**feat(generic): allow to specify a dialect when requesting data**
If a dialect is either specified via the `dialect` parameter or the
`DIALECT` HTTP header, only renderer that have that dialect listed in
their …

feat(generic): add generic RDF renderers and serializers

---

apis_core/generic/views.py

The Select2QuerysetView does not handle errors well. We override the
`post` method of the view, so we can catch exceptions and add an error
message to the response. Once the custom select2js is updated, the error
messge will be displayed in the select input field.

feat(generic): make importer return a message on error

---

apis_core/apis_metainfo/tables.py
apis_core/apis_relations/tables.py

The `render_date` methods still lingered in the `apis_metainfo` tables
module, although they were only being used in the TripleTables.
Therefore the methods werer moved and refactored.

refactor(apis_relations): move `render_date` methods into TripleTable

---

apis_core/generic/views.py

We interpreted a GET request *with* parameters but *without* a columns
parameter as the wish to have a table without any columns. But that
could also be a wish to order the table, which only appends a `sort`
parameter to existing parameters (or creates parameters if there are
none).
Therefore for now we fallback to the default columns if none are
selected, but we gain table ordering.
Closes: #1022

fix(generic): repair table columns ordering

---

apis_core/generic/api_views.py

When generating the swagger definition, the api view does not set a
renderer.

fix(generic): ModelViewSet: check if renderer exists before using it

---

docs/source/installation.rst

- removes external docker-compose repo
- re-uses readme section for simple installation
- removes windows part (WSL can be used now)

docs: improve installation chapter of the docs

---

README.md

to allow for include of the README in the docs it also replaces the line links (works only in GitHub README files) with the actual code
resolves #1075

docs: add anker to README to allow for partial include in docs

---

apis_core/apis_entities/urls.py
apis_core/apis_entities/views.py

This endpoint allows us to use autocomplete over multiple model types.
It takes a parameter `entities` which is a list of ContentType natural
keys and searches for the query in all instances of those entities
(using `generate_search_filter`, which means it uses a different search
approach for every model).
The return values of the endpoint are then prefixed with the id of the
contenttype of the results, separated by an underscore.

feat(apis_entites): add a generic entites autocomplete endpoint

---

apis_core/history/tests/test_simple_history.py

currently tests for the history plugin lack an ontology for running. This is a draft PR until we added an ontology to the testing env.

feat(history): adds tests for history plugin

---

apis_core/apis_relations/tables.py

End date wasn't displayed if there was no start date, which doesn't make
sense.

fix(apis_relations): fix relations table date render method

---

apis_core/collections/tables.py

The custom collections table contains a `target` column that lists, with
a link, the instance the collection is pointing to.

feat(collections): introduce custom collections table

---

apis_core/history/models.py

fix(history): remove verbose name from APISHistoricalRecord

---

sample_project/templatetags/sample_project.py

That way the view does not throw an exception if the `setup` management
command was not run before...

fix(sample_project): show password only if passwordfile exists

---

apis_core/relations/templates/relations/list_relations_include.html
apis_core/relations/templatetags/relations.py

The `get_relation_targets_from` method listed all possible targets of
all the relations an object might be related to. But we actually want
only a list of the targets of the relations *other* sides, seen from the
objects point of view. This is why we now also instead pass the object to
`get_relation_targets_from` and use that to check for the right targets.

fix(relations): make `get_relation_targets_from` method more targeted

---

apis_core/collections/apps.py
apis_core/collections/signals.py
apis_core/collections/templates/collections/collection_session_toggle.html
apis_core/collections/templatetags/apis_collections.py
apis_core/collections/urls.py
apis_core/collections/views.py
docs/source/features.rst

This commit implements a way to add SkosCollections to the users
session. If there are SkosCollections in the session and an model that
inherits from `apis_core.history.VersionMixin` get saved, the created
version of that object gets tagged with the SkosCollections.
Closes: https://github.com/acdh-oeaw/apis-core-rdf/issues/1066

feat(collections): allow add all changes in a session to a collection

---

apis_core/relations/querysets.py

This commit changes the default queryset for the relations listing. It
adds the `select_subclasses()` method, which "casts" the results into
their respective subclasses. This makes the listing show the correct
string representation of the instance.

feat(relations): override default queryset to include subclasses

---

sample_project/settings.py

This way it is possible for all the other apps to override and extend
the templates.

fix(sample_project): move generic and core to end of INSTALLED_APPS

---

apis_core/utils/helpers.py

If both values in get_html_diff were None or "", the diff was always
returned as an insert of the second value. This fixes it so there is no
diff shown if both values are None or "".

fix(utils): make value detection in get_html_diff more reliable

---

apis_core/apis_relations/templates/base.html
apis_core/core/templates/base.html

Instead of hardcoding the relations menu entries in the base template,
use template inheritance to add to the menu entry if the app is enabled.
Closes: #1144

feat(apis_relations): use the base template to override relations menu

---

apis_core/core/templates/registration/login.html

It was originally in `apis_metainfo`, but the `core/templates` folder
makes more sense.

fix(core): readd login.html template that was accidently dropped

---

apis_core/generic/views.py

The `create` permission does not really exist in Django, the correct
permission is called `add`.
Closes: #1173

fix(generic): replace `create` with `add` for required permission

---

apis_core/relations/serializers.py

This makes the swagger generation work again
Closes: #1178

fix(relations): set model of RelationSerializer

---

apis_core/core/templates/base.html

The Django logout system only works if a POST request with the correct
`csrf_token` is sent to the `logout` route. The previously existing link
to the `logout` route simply did not work.
Closes: #910

fix(core): replace logout link with a logout form

---

apis_core/relations/static/css/relations.css
apis_core/relations/static/js/relation_dialog.js
apis_core/relations/templates/apis_core/apis_entities/abstractentity_form.html
apis_core/relations/templates/relations/list_relations.html

HTML now supports a `dialog` element which can be used do implement a
modal like behaviour. Using this `dialog` element is a more standardized
approach than using bootstraps modal element.
This commit replaces the use of the globally defined bootstrap modal in
the apis base.html template and uses a dialog instead.

feat(relations): replace bootstrap modal with html dialog

---

apis_core/generic/templates/generic/generic_list.html

fix(generic): show verbose name instead of contenttype name in list view

---

apis_core/relations/templates/relations/list_relations.html

This makes the trigger also work with a strict CSP that does not allow
`unsafe-eval`.
Closes: #1265

fix(relations): use javascript onclick instead of htmx on:click

---

apis_core/relations/forms.py
apis_core/relations/views.py

This way we don't have to use a separate `get_form_class` in the view
that is uses the form with htmx functionality.
Closes: #1226

refactor(relations): integrate RelationFormHX into RelationForm

---

poetry.lock
pyproject.toml

The `apis_core.collections` app now uses the `nulls_distinct` argument
for a UniqueConstraint, which was only introduced in Django 5, so we
bump the minimal Django dependency.
Closes: #1271

chore(deps): bump Django min version to 5.x

---

apis_core/relations/static/js/relation_dialog.js

The dropdownParent setting defines where the autocomplete api call
results should be put in the DOM. Using the form as container we are
more flexible and can reuse the reinit_select2 event also for other
forms.

fix(relations): use form instead of hardcoding the id

---

apis_core/apis_relations/templates/apis_core/apis_entities/abstractentity_form.html

The col-one block is use by multiple apps, so it is crucial that all the
blocks call block.super, to also allow other apps to insert content.
This was forgotten when the template was introduced in
cda343687afb839f8147dbe89a70c8f8038759c0

fix(apis_relations): call block.super in the col-one block

---

apis_core/generic/static/css/more-less-column.css
apis_core/generic/tables.py
apis_core/generic/templates/columns/more-less.html
sample_project/tables.py

This pull request introduces a new `MoreLessColumn` feature to handle long text fields in tables, providing a preview with a "Show more" link that expands to reveal the full text. The changes span across CSS, template, and Python files to implement this functionality.
* **CSS for MoreLessColumn**:
* Added styles in `apis_core/generic/static/css/more-less-column.css` to handle the appearance and behavior of the "Show more" and "Show less" links.
* **Template for MoreLessColumn**:
* Created a new template `apis_core/generic/templates/columns/more-less.html` to render the preview and full text within a `<details>` element.
* **Python class for MoreLessColumn**:
* Added `MoreLessColumn` class in `apis_core/generic/tables.py` to use the new template and CSS for rendering long text fields with …

feat(generic): more/less text column template

---

apis_core/generic/views.py

get_successful_url of MergeWith view got acccidentally removed from MergeWith in commit 9e8fe5c. This is now reinstated.
Closes #1282

fix(generic): redirect to detail page after merge

---

apis_core/apis_entities/models.py
apis_core/apis_relations/signals.py

Rather than hardcoding the TempTriple update in the merge method, we use
the `post_merge_with` signal to update the existing TempTriples
Closes: #1228

fix(apis_entities,apis_relations): move TempTriple update code to signal

---

apis_core/apis_entities/models.py
apis_core/apis_entities/templates/apis_entities/partials/entity_actions_nav.html

The merge link was incorrectly pointing the merge action view that merges two objects; it has been corrected to point to the merge view that allows the user to select another object for merging.
closes #1278

fix(apis_entities): correct merge link

---

apis_core/relations/templates/apis_core/apis_entities/abstractentity_detail.html
apis_core/relations/templates/apis_core/apis_entities/abstractentity_form.html

so that overriding col-one when customising the relations table is not necessary.

refactor(relations): put relations in a block

---

apis_core/utils/settings.py

The default_settings and the list_links_to_edit functions are not used
anywhere in the apis-core-rdf codebase.

refactor(utils): drop unused functions

---

apis_core/core/static/css/core.css

Set text-decoration property to none for
hovered footer links which contain icons to
prevent whitespace between links/icons from
getting underlined (default effect when text
links are hovered).
Solves one of the issues described in https://github.com/acdh-oeaw/apis-core-rdf/issues/1343.

fix(core): don't underline hovered footer icon links

---

apis_core/apis_entities/templatetags/apis_entities.py
apis_core/apis_relations/templates/apis_core/apis_entities/abstractentity_detail.html
apis_core/apis_relations/templates/apis_core/apis_entities/abstractentity_form.html
apis_core/apis_relations/templates/apis_relations/entity_relations_multiple_cards.html
apis_core/apis_relations/templatetags/apis_relations.py
apis_core/apis_relations/utils.py
apis_core/history/utils.py
apis_core/utils/helpers.py

This commit moves a couple of methos and templatetags into the
`apis_relations` module, that were previously spread over the `utils`
and the `apis_entities` module. Having them contained in the
`apis_relations` module moves us one step further in being able to allow
disabling the `apis_relations` module.

refactor(apis_relations): move external methods into module

---

apis_core/relations/forms.py
apis_core/relations/static/js/relation_dialog.js

* fix(relations): if there is only one target, use specific autocomplete
When the relation form only has to provide autocomplete for a specific
target type, we can use the generic autocomplete endpoint. This allows
also to create entities by pasting URIs.
* fix(relations): force relation form select2 to use html

relations: make autocomplete use specific endpoint

---

apis_core/core/templates/partials/footer-left.html

Remove (as per the HTML spec) discouraged `title` attributes from links in footer template and instead use their values for missing (also per the HTML spec) `alt` attributes on images they enclose.
Solves one of the issues described in https://github.com/acdh-oeaw/apis-core-rdf/issues/1343.

fix(core): remove title attributes, add alt attributes

---

apis_core/generic/views.py

If we create `fake_field` by simply using `getattr` on the
`annotations.items()` we actually get the original field and then change
its name in the next line. But thats not what we want, because that
changes the field for the model it belongs to. We only want a temporary
field, so we can add it to the `extra_columns`.
Closes: #1346

fix(generic): use copy instead of working with the original field

---

apis_core/apis_entities/static/css/E53_Place_popover.css
apis_core/apis_entities/static/css/apis_entities.css
apis_core/apis_entities/templates/apis_core/apis_entities/abstractentity.html
apis_core/apis_entities/templates/apis_core/apis_entities/e53_place_detail.html
apis_core/apis_entities/templates/apis_entities/partials/entity_actions_nav.html
apis_core/apis_entities/templates/apis_entities/partials/entity_base_nav.html
apis_core/apis_entities/templates/apis_entities/partials/next_url.html
apis_core/apis_entities/templates/apis_entities/partials/prev_url.html
apis_core/apis_entities/templates/columns/duplicate.html
apis_core/apis_relations/static/css/apis_relations.css
apis_core/apis_relations/templates/apis_relations/relations_detail_generic.html
apis_core/core/static/css/core.css
apis_core/core/static/css/override_bootstrap.min.css
apis_core/core/templates/base.html
apis_core/core/templates/partials/bootstrap4_css.html

Move leftover inline styles from HTML templates to static CSS files.
Closes #1258
---
Not included are the scroll button styles already covered by #1234 and styling applied in Python code as that's harder to untangle. Ex. https://github.com/acdh-oeaw/apis-core-rdf/blob/cda343687afb839f8147dbe89a70c8f8038759c0/apis_core/apis_relations/forms.py#L49-L54
The styles in `apis_relations.css` may be redundant as they belong to `relations_detail_generic.html`, see #1259, but I didn't want to leave strays. I've added TODO comments in the file to make note of that.

refactor (various) to move inline styles

---

apis_core/apis_entities/urls.py
apis_core/apis_metainfo/urls.py
apis_core/core/templates/partials/footer-left.html
apis_core/core/urls.py
apis_core/urls.py

This commit refactors the whole `apis_core.urls` module. It splits up
different apps urls in separate blocks that are only included if the app
is actually enabled. It also moves some of the app specific routes to
their apps, instead if cluttering the main urls.py file with the
includes.
Closes: #1170

refactor(apis_core): refactor the urls entrypoint

---

apis_core/core/static/css/core.css

Set display property of links in site footer
which are visualised by icons – which contain
images or <span> tags for Material Symbols –
to inline-block to make them fit the icons'
dimensions. Prevents links that are smaller
in size than their visual content, which can
cause unexpected behaviour when hovering.
Solves one of the issues described in #1343.

fix(core): fix footer link dimensions

---

apis_core/generic/views.py

Make the column choices have the same format as the filter form labels
by running the field names through the `pretty_name` method.
Closes: #1028

fix(generic): run the columns names through `pretty_name`

---

apis_core/core/templates/partials/footer-left.html

The leading slashes seem to lead to confusing errors from the django
debug toolbar and the `url` method of the configured storages remove it
anyway:
https://github.com/django/django/blob/d71c588d83e58e83bdd9ea8bf03724d10f02a8bd/django/core/files/storage/filesystem.py#L225
Closes: #1339

fix(core): remove leading slash from static files

---

apis_core/apis_entities/templates/apis_core/apis_entities/abstractentity_form.html
apis_core/apis_entities/templatetags/apis_entities.py

Remove the merge form from the default entities edit view, given that
there is a more powerful merge view that should be used instead.
Closes: #1285

fix(apis_entities): remove merge form from the entities edit view

---

apis_core/generic/views.py
apis_core/utils/helpers.py

This allows the calling function to define how it wants the
`create_object_from_uri` function to communicate errors. This is not
pretty and we might want to rethink that function in the future, but for
now it allows the two places that call that function to both keep
working.
Closes: #1405

fix(utils): add a `raise_on_fail` argument to the object create function

---

apis_core/relations/static/js/relation_dialog.js

This pull request includes a change to the `tohtml` function in the `relation_dialog.js` file to enhance the functionality of the `select2` initialization.
Enhancements to `select2` initialization:
* [`apis_core/relations/static/js/relation_dialog.js`](diffhunk://#diff-348bcae18586c8a83583596ccf46a4858b42bb5886c6b65f736d894456d9fcd4L8-R8): Modified the `form.querySelectorAll` method to include additional selectors `.modelselect2multiple` and `.modelselect2` for initializing `select2`.

fix(relations): support modelselect2multiple fields

---

apis_core/history/api_views.py
apis_core/history/urls.py

Remove the TempTripleHistoryLogs API view, because it has a hardcoded
dependency on the TempTriple model and therefore *needs* the
`apis_core.apis_relations` app in the INSTALLED_APPS.
Together with the API view we are also dropping the url pointing to the
API view.

fix(history): drop TempTripleHistoryLogs api view

---

apis_core/history/utils.py

Only import the `get_generic_triple_table` method if the
`apis_core.apis_relations` app is in the list of INSTALLED_APPS.

refactor(history): move import statement into `if` block

---

apis_core/relations/templates/relations/list_relations_include.html
apis_core/relations/templates/relations/list_relations_include_tabs.html

this way `list_relations_include_tabs` can inherit from the `list_relations_include` template and not contain redundant code to fetch the relations data
@b1rger the large diff is not my fault, it's djlint, my change is only 3 lines :-0

refactor(relations): put display logic of relations in a block

---

apis_core/apis_entities/filtersets.py
apis_core/apis_relations/filters.py

Move the Property and Triple related filters and methods to the
`apis_relations.filters` module instead of keeping them in the
`apis_entities.filtersets` module. This makes the whole module more
readable and moves the filters and methods closer to the models they are
working with. Additionaly, this makes it possible to only import the
fitlers and methods if the `apis_relations` app is actually part of the
INSTALLED_APPS list.

refactor(apis_entities, apis_relations): move filters and methods

---

apis_core/relations/filtersets.py

Replace the "hardcoded" `subj_class` and `obj_class` filters in the
RelationFilterSet with more dynamic versions that take a list of models
that can be possilbe choices. If there is only one choice, the filter is
simply not added.
Closes: #1390

feat(relations): limit the number of subj/obj models in filter

---

pyproject.toml

We don't want to ignore unused dependencies overall, but only specific
ones.
Closes: #1417

chore(deptry): replace ignore with per_rule_ignore

---

.github/workflows/djlint.yml

The workflow we are including does call djlint with `--check` option,
which checks the formatting of the the template, but does not lint the
template. Therefore using `Formatter` instead of `Linter` in the
template is more correct.
Closes: #1371

ci(djlint): change the name of the workflow to reflect what it does

---

apis_core/generic/abc.py

Some models do not have an `id` attribute, therefore it makes sense to
check for its existence before using it in the __repr__ string.
Closes: #1450

fix(generic): check for attribute `id` before using it

---

apis_core/apis_entities/templates/apis_entities/partials/linked_open_data.html

We want to provide a link to allow updating/enriching the entity with
data from external sources, but there is not really an icon that
reflects that action. So we use a simple link instead of an icon.

fix(apis_entities): replace the update link icon with text

---

apis_core/generic/views.py
docs/source/customization.rst

Instead of overriding the `get_paginate_by` method of the
TableMixinBase, we now override the `get_table_pagination` method. This
allows to also set the `table_pagination` setting in the table
itself, therefore providing the means to disable the pagination
alltogether.
Closes: #1444

feat(generic): allow to disable pagination in table class

---

apis_core/generic/views.py

Some parent views need a `.template_name` set, but we have our own
fallbacks, so we don't depend on that attribute to be set. So we handle
the missing attribute gracefully.

fix(generic): catch exception if .template_name is not set

---

apis_core/generic/forms/__init__.py
apis_core/generic/views.py

The form is used in the `MergeWith` view, so it should be called
accordingly.

refactor(generic): rename GenericMergeForm to GenericMergeWithForm

---

apis_core/apis_entities/abc.py

Swap `E3_Place` `latitude` and `longitude` fields
so that the fields appear in the order in which
geographic coordinates are given.
Relevant for views/tools which base the default
order of model fields on how they are originally
defined.
Closes: #1475

refactor(apis_entities): reorder E3_Place coordinate fields

---

apis_core/apis_entities/static/css/apis_entities.css
apis_core/generic/static/css/generic.css
apis_core/generic/templates/generic/generic_content.html

The object action classes are used in the generic templates, therefore
they should be moved to a `generic.css` stylesheet which is included in
the `generic_content.html` base template.
Closes: #1469

fix(generic,apis_entities): move action classes to generic app

---

apis_core/apis_entities/models.py

Fixtures should contain all the data anyway, so the automatic creation
of the default uri should be skipped.
Closes: #1473

fix(apis_entities): disable create_default_uri during fixture loading

---

apis_core/core/templates/base.html

We use select2 only in conjunction with django-autocomplete-light,
therefore it doesn't make sense to include it separately.
Closes: #1481

feat(core): drop inclusion of select2 javascript and css

---

.github/workflows/django-tests.yml
sample_project/settings.py
sample_project/settings_tests.py

We only use the new style relations in the sample project, so we can
drop the old ones.

chore(sample_project): drop `apis_relation` from INSTALLED_APPS

---

docs/source/features.rst

docs(history): add documentation on some management commands

---

apis_core/core/middleware.py
apis_core/core/static/css/maintenance.css
apis_core/core/templates/maintenance.html
docs/source/configuration.rst

Add a MaintenanceMiddleware that allows to set APIS in maintenance mode.
Maintenance mode allows superusers to access the site, but all other
requests get a simple maintenance page as a response.
This can be enabled by adding
`apis_core.core.middleware.MaintenanceMiddleware` to
`settings.MIDDLEWARE`. To active the maintenance mode simply create a
`/tmp/apis_maintenance` file. To deactivate maintenance mode, remove
that file.
Closes: #1296

feat(core): introduce a MaintenanceMiddleware

---

apis_core/apis_metainfo/signals.py

Some model instance don't have a primary key thats called `id` or don't
have a numeric primary key. Use the `pk` attribute and check if its an
integer before using it to filter Uris.

fix(apis_metainfo): check for numeric id before listing related Uris

---

apis_core/apis_metainfo/migrations/0001_initial.py
apis_core/apis_metainfo/models.py

The InheritanceForeignKey was previously used by the Uri model instead
of a foreign key. After refactoring the Uri to use a generic foreign
key, this can be dropped.

chore(apis_metainfo): drop unused field classes

---

apis_core/relations/forms.py
apis_core/relations/static/js/relation_dialog.js

The reinit_select2 functionality is now in a separate
`rel_reinit_select2` function which is run every time the js is included
*and* when the `reinit_select2` trigger is received (though not sure if
thats even needed now).
In addition the javascript is included in the relation forms Media
class, so that the js is included with every relation form and thus the
`rel_reinit_select2` function is executed everytime the form in loaded
which is what we actually want to make the select2 work everytime.
Closes: #1544

fix(relations): refactor js and add it to forms Media class

---

apis_core/generic/forms/__init__.py

Unconditionally importing the SkosCollection class leads to an error, if
the `collections` app is not enabled. This commit fixes this by using
the app registry to access the model.
Closes: #1554

fix(generic): only add collections if app is installed

---

apis_core/relations/templates/relations/list_relations.html

If the table contains no data, it's better to now show it at all instead
of showing empty tables.
Closes: #1543

fix(relations): hide empty relations tables

---

apis_core/generic/filtersets.py
apis_core/generic/forms/fields.py
apis_core/generic/templates/widgets/includeexclude_multiwidget.html

feat(generic): add a collections filter

---

apis_core/apis_entities/templates/base.html
apis_core/core/templates/base.html
apis_core/relations/templates/base.html
sample_project/settings.py

- feat(relations): move relations menu to relations app
- feat(apis_entities): move entities menu to apis_entities app
- refactor(sample_project): rearrange app order

Move menus into apps

---

apis_core/generic/abc.py
apis_core/generic/templates/base.html
apis_core/generic/templatetags/generic.py

This commit introduces a template tag in the generic module that lists
all content types that inherit from the Generic Model but are not
Collections, Entities, Relations or History models.
This templatetag is then used to create a menu entry to manage those
types.
Closes: #1582

feat(generic): introduce generic menu entry

---

.github/workflows/pages.yml

Because the `settings_test` file was dropped

ci(docs): use default sample_project settings for building documentation

---

.github/workflows/add-to-project.yml

Add `pull_request` trigger to `add-to-project`
workflow so both issues and PRs are added to
the Prosnet project.
Update workflow `name` to reflect the change.
Resolves: #1593

ci: run add-to-project workflow also on PRs

---

apis_core/apis_entities/templates/base.html
apis_core/apis_entities/templatetags/apis_entities.py

This replaces the `entities_verbose_name_plural_listview_url`
templatetag with a more generic one that simply lists the entity content
types. This is more similar to how it is done in the generic menu entry.
Closes: #1576

feat(apis_entities): replace entity list templatetag with generic one

---

apis_core/relations/templates/base.html
apis_core/relations/templatetags/relations.py

This introduces the `get_relation_content_types` template tag, which
simply lists the relation content types. This is then used instead of
the `relations_verbose_name_listview_url` templatetag to get a list
of relations and their list view urls. This approach allows to only
show the relations, the accessing user has permission to view.
The `relations_verbose_name_listview_url` templatetag is being dropped.
Closes: #1577

feat(relations): use more generic template tag to list relations

---

sample_project/settings.py

The sequence in the INSTALLED_APPS list defines where in the main menu
the apps menu item will be. We want the generic menu item to be the one
on the right.

feat(sample_project): move generic app up in INSTALLED_APPS list

---

apis_core/generic/views.py

Apparently the solution with the `subclasses` attribute does not work
anymore, so lets check for the `parent_link` and hope we don't exclude
too many fields.
Closes: #1297

fix(generic): don't show subclasses in columns selector

---

apis_core/collections/models.py
apis_core/collections/templates/collections/collection_object_collection.html
apis_core/collections/templatetags/collections.py
apis_core/collections/urls.py
apis_core/collections/views.py

We provide a way of toggling collections by simply allowing them to
reside in each other (two collections A and B, A is in collection B and
B is in collection A).

feat(collections): implement toggling collection without the parent

---

apis_core/apis_metainfo/models.py

The `get_web_object` was used by the former relations app, but is not
used anymore.

refactor(apis_metainfo): drop `get_web_object` method

---

apis_core/apis_entities/migrations/0001_initial.py
apis_core/apis_metainfo/migrations/0002_auto_20220201_1241.py

fix(apis_metainfo): drop references to `apis_metainfo.collection`

---

apis_core/apis_entities/templates/base.html

Changes the current sort order of entity model
classes in the entities menu in `base.html` from
(presumably) by `ContentType` `id` to alphabetical by `ContentType` `name`, which is based on the
model's `verbose_name`.
Resolves: #1657

fix(apis_entities): reorder entity menu items

---

apis_core/collections/templates/collections/collection_object_collection.html
apis_core/collections/templatetags/collections.py

The toggle templatetags were written to work with the ids of
SkosCollectionContentObjects, but SkosCollectionContentObjects are 1:1
relations to any object, so listing their IDs in a template tag does not
make sense.
This commit fixes those templatetags and also makes them more resistent
against errors (and it also shows the errors, if there are any).

fix(collections): repair the new collection toggle templatetags

---

apis_core/relations/forms/__init__.py

With the refactoring done in 29d39dab2644980f51c7d09a6a24695e4b8cdde5 we
don't know anymore which target type the relation create form refers to.
This leads to the creation form using a different autocomplete endpoint,
one where we don't have external autocomplete results.
This commit fixes this partially for Relations that allow only **one**
specific type of relation target.
Closes: #1676

fix(relations): repair the relation target autocomplete

---

apis_core/generic/templatetags/generic.py

The `_get_FIELD_display()` method coerces values to string, which is not
ideal if we for example want to format a value differently in the
templates. We now use the `get_{field.name}_display()` method instead if
it exists (which is basically the same as the `_get_FIELD_display()` if
the value has choices defined) and we default directly to the value of
the field.
This way we still have lists as lists in the template.

fix(generic): don't coerce values to string in modeldict

---

docs/source/configuration.rst

Change mentions of (suspected typo) `APIS_BASE_URL` to `APIS_BASE_URI` (L to i).
Closes: #1680

docs(configuration): correct references to APIS_BASE_URI

---

apis_core/generic/views.py

The `parent_link` attribute is apparently only set when the model
inherits from a concrete model, which is not the case for all the models
inheriting from AbstractEntity ("When True and used in a model which
inherits from another concrete model, indicates that this field should
be used as the link back to the parent class", from
https://docs.djangoproject.com/en/5.1/ref/models/fields/#django.db.models.OneToOneField.parent_link
Lets use the `auto_created` field instead, which "indicates if the field
was automatically created, such as the OneToOneField used by model
inheritance" - this might have side effect, but "auto_created" looks
like it should not be part of a column choice selector.

fix(generic): use different attribute for excluding column choices

---

apis_core/apis_entities/models.py
apis_core/apis_entities/urls.py
apis_core/apis_entities/views.py
apis_core/generic/abc.py
apis_core/generic/urls.py
apis_core/generic/views.py

- **refactor(generic,apis_entities): move duplicate logic to GenericModel**
- **refactor(apis_entities): drop legacy EntityToContenttypeConverter**

Move remaining duplicate logic to generic and drop legacy converter

---

apis_core/apis_entities/api_views.py

Without the permission class, DRF falls back to the default permission
class, which might sometimes be the DjangoModelPermissions class. This
class, however, uses the queryset to assess the permission of the user.
Given that this view does not use a queryset and it only forwards a
request, it makes sense to simply set the permission class to allow any
request.
Closes: #1678

fix(apis_entities): add permission class to GetEntityGeneric view

---

apis_core/collections/filters.py
apis_core/generic/filtersets.py
apis_core/generic/forms/fields.py
apis_core/generic/templates/widgets/row_column_multiwidget.html

Instead of providing one dropdown for selecting the collections and one
dropdown for selecting include or exclude, we now provide one dropdown
for selecting collections to exclude and one dropdown for selections to
include.
This introduces a RowColumnMultiValueField (+ widget) and uses this one
instead of the IncludeExcludeField (+ widget), so we drop the
IncludeExcludeField (+ widget).

feat(generic): refactor the collections filter

---

apis_core/generic/views.py

This method was lost in f2e0b2f9ac5f43154049284529e9ec9e1af393c7 but is
actually useful, if we want to override the queryset for the list view.
In the long run we might replace that logic with a custom Generic
Manager, but for now we still use this override.

feat(generic): readd the `get_queryset` method to the List view

---

apis_core/core/templates/base.html

Since version 2 of htmx it is possible to configure htmx using `meta`
tags in the document header. Using this approach we can drop the event
listener that we used before to configure the htmx swap behaviour for
204 status codes.

refactor(core): replace eventlistener with meta config

---

.gitignore

The `.mo` files should not be part of the source repository, but be
generated on installation

build(gitignore): ignore `*.mo` files

---

apis_core/collections/templates/collections/collection_object_collection.html

https://docs.djangoproject.com/en/5.1/topics/i18n/translation/#std-templatetag-blocktranslate:
"To translate a template expression – say, accessing object attributes
or using template filters – you need to bind the expression to a local
variable for use within the translation block."

fix(collections): use blocktranslate with `with` statement

---

apis_core/core/templates/base.html

If we only set the responseHandling object with the setting for the 204
response code, we replace all the other defaults. Lets instead set the
204 together with the defaults.

fix(templates): repeat the default settings for htmx.responseHandling

---

apis_core/generic/templates/generic/generic_enrich.html
apis_core/generic/templates/generic/generic_list.html
apis_core/generic/templates/generic/generic_merge.html
apis_core/generic/templates/generic/generic_selectmergeorenrich.html

https://docs.djangoproject.com/en/5.1/topics/i18n/translation/#std-templatetag-blocktranslate:
"To translate a template expression – say, accessing object attributes
or using template filters – you need to bind the expression to a local
variable for use within the translation block."

fix(generic): use blocktranslate with with statement

---

.github/workflows/django-messages.yml
apis_core/apis_entities/locale/de/LC_MESSAGES/django.po
apis_core/collections/locale/de/LC_MESSAGES/django.po
apis_core/core/locale/de/LC_MESSAGES/django.po
apis_core/documentation/locale/de/LC_MESSAGES/django.po
apis_core/generic/locale/de/LC_MESSAGES/django.po
apis_core/relations/locale/de/LC_MESSAGES/django.po

This leads to too much noise, because we would have to update the
translations basically every time the linenumber of a text changes.

chore(translations): remove exact location from po files

---

docs/source/conf.py

Add Sphinx extension which converts references to
headings within the documentation to clickable links.

docs: add Sphinx autosectionlabel extension

---

apis_core/apis_entities/templates/apis_entities/partials/entity_actions_nav.html
apis_core/apis_entities/templates/apis_entities/partials/entity_base_nav.html
apis_core/generic/static/css/generic.css
apis_core/generic/templates/columns/delete.html
apis_core/generic/templates/columns/edit.html
apis_core/generic/templates/columns/view.html

Switch styling for object actions view, edit, delete from Boostrap's built-in colour classes which convey meaning to custom CSS classes. This gathers all object action classes in one place (duplicate, merge, history actions already use custom CSS classes) and allows independent use of the built-ins.
Resolves: #1765

refactor(generic): use custom CSS classes for object actions

---

apis_core/apis_entities/templates/apis_entities/partials/linked_open_data.html

closes #1726
both internal and external links will open in a new window/tab as these links take the user away from the APIS web app.

feat(apis_entities): open URIs in a new window/tab

---

apis_core/apis_entities/locale/de/LC_MESSAGES/django.po
apis_core/apis_entities/templates/apis_entities/partials/entity_base_nav.html
apis_core/history/locale/de/LC_MESSAGES/django.po
apis_core/history/templates/apis_entities/partials/entity_base_nav.html
sample_project/settings.py

update the templates to separate `history` better from `core`.
resolves #1780

fix: move history nav entry template to history

---

apis_core/generic/templates/generic/partials/default_model_field_value.html

The default should be to *not* show empty lists.
Closes: #1797

fix(generic): templates: show only existing values

---

README.md

Setting up a Django app is possible with any Python project management
tool. Referencing one specifically just leads to confusion with users.

docs(readme): remove references to poetry from readme

---

apis_core/generic/templates/base.html
apis_core/generic/templates/generic/generic_content.html

To make it easier for users to inject css files *after* the inclusion of
the `generic.css` file we move this inclusion to the `base.html` block.
This way it is included on the same level as the css files of the other
apps.

feat(generic): move css include into the base template

---

apis_core/urls.py

This is mostly so that mkdocs finds the module

docs(apis_core): add basic docstring to urls module

---

apis_core/relations/templatetags/relations.py

so that the relations list table class specific to a target type has higher precendence over the relations list table class.
fixes #1830

fix(relations): add {ObjectType}RelationsTable before RelationsTable suffix

---

apis_core/generic/abc.py
apis_core/generic/serializers.py

The name is the human readable representation of the model and this can
contain spaces, which is not allowed as part of a rdf namespace.

fix(generic): use `.model` instead of `.name.lower()`

---

apis_core/generic/helpers.py

some methods already pass lists as a query, so split does not work on
those arguments.
Closes: #1840

fix(generic): only use `.split` on strings

---

apis_core/apis_metainfo/utils.py
apis_core/generic/forms/fields.py
apis_core/generic/importers.py
apis_core/generic/views.py
apis_core/utils/helpers.py

The `create_object_from_uri` uses the Uri model, so it makes more sense
if it is located in the app that also contains this model. Besides,
having the method in the `utils.helpers` module led to circular import
errors.
Closes: #1816

fix(apis_metainfo): move method from utils to apis_metainfo.utils

---

apis_core/generic/generators.py

APIS does not have to run under `/apis`, so we exclude everything that
contains `/api/{contenttype}/` instead of everything that starts with
`/apis/api/{contenttype}`. Still a hack, but yeah...

fix(generic): make endpoint enumeration exclude more generic

---

apis_core/core/templates/base.html

Use Bootstrap 5 CSS classes for text alignment
in site footer in base template.
This fixes the alignment of the "Imprint" link
(where available) on the right-hand side of the
site footer to mirror the icons on the left.
The alignment of the icons does not noticeably
change, presumably because left-(i.e. start-)
aligned text is the default. (The CSS classes
used until now had no effect on alignment
anymore; they are leftovers from Bootstrap 4.)
Closes: #1856

fix(core): fix text alignment in site footer

---

apis_core/core/static/css/core.css
apis_core/core/templates/base.html

We drop the bootstrap `btn-danger` class from the back to top button
element and instead set the values manually.
Closes: #1855

feat(core): replace hardcoded bootstrap class with custom values

---

apis_core/apis_entities/api_views.py

This is mostly to calm the openapi generator from drf_spectacular,
because it could not find a serializer in this APIView

fix(apis_entities): use implizit one-off serializer for GetEntityGeneric

---

docs/source/configuration.md
docs/source/customization.md
docs/source/development.md
docs/source/features.md
docs/source/glossary.md
docs/source/installation.md
docs/source/ontology.md

Correct grammar, spelling errors (including
proper names, acronyms, inconsistent spellings
of headlines and regular words), missing
or misleading punctuation.
Closes: #1752

docs: fix grammar, spelling, punctuation

---

apis_core/utils/rdf.py

When we receive a boolean `True` value as part of a triple, we actually
want to know if the triple exists in the graph. We therefore have to
replace the `True` with `None` (otherwise we would check if there is a
triple containing `True`, but `None` is a catchall value).
Closes: #1905

fix(utils): when resolving, also handle boolean `True` value

---

apis_core/apis_entities/triple_configs/E53_PlaceFromWikidata.toml

For the place labels we want first and foremost the german label, then
fall back to the english label, then the official one and only as last
fallback use the default label.
Closes: #1863

fix(apis_entities): reorder label & select place label using languages

---

apis_core/generic/serializers.py

The rdflib namespaces always ends with the last slash in the URI. So if
we append a string to a namespace that contains a slash, the prefix is
not matched correctly because it maps to another namespace.
Therefore we remove the slashes from the suffixes.
Closes: #1876

fix(generic): replace slashes with underscores in ATTRIBUTES ids

---

apis_core/history/locale/de/LC_MESSAGES/django.po
apis_core/history/models.py
apis_core/history/tables.py
apis_core/history/templates/history/columns/reset.html
apis_core/history/templates/history/reset.html
apis_core/history/urls.py
apis_core/history/views.py

Allow to revert objects to a earlier state using the history view
- feat(history): introduce view to reset object to a history version
- feat(history): add `get_reset_url` helper method to history models
- feat(history): add a link to the reset view to the history table
Closes: #283

Allow to revert objects to a earlier state

---

apis_core/history/views.py

This reverts commit ae5fecd44b71d1971e62ce31ee46ea46ae6fa31f.
Using `GenericModelMixin` as a base for the HistoryView was actually the
correct approach, because we *are* primarily looking at *one* object and
we use the SingleTableMixin to list the related history data.
Closes: #1919

Revert "feat(history): use history queryset for views"

---

apis_core/generic/importers.py

The importer always provides a list of values that can be imported, but
usually the fields don't contain lists. So we default to the first
element in the list as the value to be imported.

fix(generic): use first element of list for enriching entities

---

apis_core/generic/importers.py

The actual object instance already exists at this point, so if there is
an exception it should be gracefully handled instead of everything
blowing up

fix(generic): catch exception if relation could not be imported

---

apis_core/core/static/css/core.css
apis_core/core/templates/base.html

Its not used anymore anywhere, we now use standard html dialog
everywhere
Closes: #1917

fix(core): drop `modal` block

---

apis_core/relations/models.py

We decided to not support multiple types of relation targets, so a
relation should only have *one* subj_model or *one* obj_model.
Closes: #1923

feat(relations): warn user when obj_model or subj_model are lists

---

.github/workflows/django-messages.yml

the workflow checks changes using git diff. now that we have a `uv.lock`
file in the repository (57761c4523caca315c38cedb0462f01ff8f130b5) this
file gets updated if we run `uv` without the `--frozen` flag which would
then lead to a changed repository state

ci: use --frozen for uv in message check workflow

---

apis_core/relations/forms/__init__.py

This commit separates the code blocks for the edit and create
functionalities of the RelationForm. The subj and obj fields are not
editable also for the edit form.
Closes: #1922

fix(relations): make relation field editable again

---

apis_core/generic/forms/fields.py

The field should only try to import when we are working with an URI and
it should raise an error if the import fails.

feat(generic): make ModelImportChoiceField more robust

---

apis_core/generic/templates/apis_core/generic/genericmodel_card.html
apis_core/generic/templates/generic/generic_detail.html
apis_core/generic/templates/generic/partials/object_card.html
apis_core/relations/templates/apis_core/relations/relation_card.html
apis_core/relations/templates/apis_core/relations/relation_card_table.html

- **feat(generic): use `template_list` templatetag in `generic_detail.html`**
- **feat(relations): introduce a `relation_card.html` template**
- **feat(relations): introduce a `relation_card_table.html` template**
Closes: #1728

improve generic object template lookup & improve relation detail view

---

apis_core/generic/helpers.py

We enhance the list of mro_paths (which are used for class and template
lookups) to also include shorter versions of paths. Currently, for the
class `foo.bar.baz.MyClass` the list contained the whole path, which can
be cumbersome. For example, when working with templates it looks up the
template in `foo/bar/baz/myclass_{suffix}.html`. With this change we
also add a path to the lookup list containing only the class name and
the direct parent module, so for the example above this would be
`baz.Myclass` and the template lookup path list would then also contain
`baz/myclass_{suffix}.html`.

feat(generic): add options to mro_paths

---

apis_core/collections/views.py

The `content_type` is a Django view attribute that represents the HTTP
content type so we should not overwrite it with the content_type of our
object.

fix(collections): rename view attribute to `obj_content_type`

---

apis_core/generic/locale/de/LC_MESSAGES/django.po
apis_core/generic/templates/generic/generic_create.html
apis_core/generic/views.py

The template name for the generic create view was set to
`generic/generic_form.html` which means that it only used this
template and did not allow to overload it for specific content types.
This commit replaces the hardcoded template name with a template name
suffix `_create` which means the view will look for a matching template
and fall back to `generic/generic_create.html` if none found.
Closes: #1982

feat(generic): use template lookup for create view

---

apis_core/generic/importers.py

If one of the import methods did not raise an exception, but instead
returned simply None (like our rdf importer), the request method simply
returned None, but that leads to errors.
Therefore we make the checks for the data more explicit and only return
the data at then end or an empty dict if the data is still None.

fix(generic): fix the request logic of the importer

---

apis_core/relations/templates/relations/relation_form.html

The `generic_form` template was renamed to `genericmodel_form`

fix(relations): let template inherit from correct template

---

apis_core/apis_entities/templates/apis_core/apis_entities/e53_place_list.html
apis_core/apis_entities/templates/apis_core/apis_entities/e53_place_map.html

The base template was renamed to `genericmodel_list.html`

fix(apis_entities): update base template for place templates

---

.github/workflows/linters.yml

Update `names` of `steps` in `linters.yml` workflow file to correspond to the tools/`jobs` that are run.
Closes: #2053

ci(workflows): fix linter jobs step names

---

.github/workflows/pages.yml
pyproject.toml

...and configure coverage to ignore `tests` folders

ci(coverage): move coverage options to pyproject.toml

---

apis_core/apis_entities/triple_configs/E53_PlaceFromDNB.toml
apis_core/utils/test_rdf.py
apis_core/utils/testdata/wutaishan.rdf

This pull request adds support for handling DNB "NaturalGeographicUnit" places in the RDF parsing logic and tests. The main changes include updating filter configuration to recognize this type, adding a corresponding test case, and providing a sample RDF file for test data.
* Updated `E53_PlaceFromDNB.toml` to include a filter for `"rdf:type" = "gndo:NaturalGeographicUnit"`, enabling the system to recognize and process this entity type.
**Tests:**
* Added a new test case `test_dnb_geographic_unit` in `test_rdf.py` to verify correct parsing of a DNB NaturalGeographicUnit RDF file, checking label extraction and absence of latitude/longitude data.
* Added new sample RDF file `wutaishan.rdf` containing a DNB NaturalGeographicUnit for use in tests.
closes #2074

import geographic place

---

apis_core/apis_entities/triple_configs/E21_PersonFromDNB.toml
apis_core/utils/test_rdf.py

If no `forename` is set, fall back to `preferredNameEntityForThePerson`
Closes: #2086

fix(apis_entities): use preferredNameEntityForThePerson in importer

---

apis_core/generic/templates/generic/genericmodel_list.html
apis_core/relations/models.py
apis_core/relations/templates/base.html
apis_core/relations/templates/relations/relation_list.html

This pull request improves how relation names are displayed throughout the UI by introducing a new method to show both the name and reverse name of relation models when appropriate. This enhances clarity for users when viewing lists of relations. The main changes are grouped below:
**Display improvements for relation names:**
* Added a new class method `name_and_reverse_name` to relation models, which returns a string combining the name and reverse name if they differ, or just the name if they are the same.
* Updated the dropdown list in `base.html` to use `name_and_reverse_name` instead of just `name`, making relation names more descriptive in the UI.
* Modified the generic list template to allow child templates to override the list view header, enabling the new relation name display.
* …

relations label

---

apis_core/apis_entities/tables.py

This pull request makes a minor documentation update to the `DuplicateColumn` class in `apis_core/apis_entities/tables.py`, clarifying that the column displays a duplicate button rather than a view button.

docs(apis_entities): correct DuplicateColumn docstring to clarify button type
