acdh-oeaw/apis-core-rdf

apis/settings/base.py, apis/settings/base_dev.py, apis/settings/settings_test_ci.py, apis/urls.py, apis/wsgi.py, pyproject.toml
This commit replaces the stale `apis` module in this project with
the updates `apis` module that is part of the `apis-rdf-devop`
repository. It also updates the `pyproject.toml` to install this
module.
=> Merge the devops apis module into the apis-core-rdf project

apis_core/apis_entities/models.py
This commit refactors the `get_all_entity_classes()` method. Instead of loading a
hardcoded module we simply get a list of all models and check wether they are
children of TempEntityClass (or in the future of another class that is the root
of all entities). This way we can also loose the inspect import.
I tested the changes in an test instance. Before merging this PR I would like
to clarify the reason of or remove the `ent_class` comparison.
=> apis_entities: refactor get_all_entity_classes

apis_core/apis_relations/views.py, apis_core/helper_functions/caching.py
This fixes a double import that was introduced in e90f0a8 and reintroduces a
change from 90a1ad5 that got lost.
=> Fix double import and reintroduce lost change

.github/workflows/pages.yml, pyproject.toml
=> Add action to automatically build documentation

apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html, apis_core/apis_metainfo/models.py, apis_core/apis_metainfo/test_models.py
* Add  **Source**  to an entity's detail view template.
* Always use a source's name (`orig_filename` field) if it is set, don't default to only ID just because the field for author info is empty.
**Additional context**
This class needs documentation added to it to explain its purpose and to make its fields clearer. To me it seems the fields are in need of a general overhaul. -> They weren't super useful for our purposes, and some changes in this PR work around that problem.
**Checklist**
=> Improve how "source" data is displayed on admin frontend

apis_core/apis_entities/models.py
Now that the relations are replaced by TempTriples, the former logic of
matching on the modelname of the relation does not work anymore. Instead
we use two simple update statements to TempTriple filters.
@steffres I'm assigning this to you, because according git `git blame` you wrote this for loop https://github.com/acdh-oeaw/apis-core-rdf/blob/65fa513d284130f3ef095afad98b42a490342437/apis_core/apis_entities/models.py#L320 - maybe you can shed some light on whether it contains logic this fix should also contain.
=> apis_entities: fix update of relations when merging

apis_core/apis_entities/models.py, apis_core/apis_entities/signals.py, apis_core/apis_metainfo/models.py, apis_core/apis_metainfo/signals.py
- feat(apis_metainfo): introduce duplication signals
- feat(apis_entities): introduce merge_with signal
=> Introduce duplicate and merge_with signals

apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html
This way we can add custom content to the entity header
=> feat(apis_entities): add additional blocks to generic detail template

apis_core/apis_entities/models.py
This commit introduces a `merge_fields` method in the TempEntityClass.
It copies information for the relevant fields in TempEntityClass and can
be extended by subclasses to implement custom logic for copying custom
subclass fields.
Closes: #140
=> feat(apis_entities): copy fields when merging entities

apis_core/utils/test_rdf.py, apis_core/utils/testdata/achensee.rdf, apis_core/utils/testdata/oeaw.rdf, apis_core/utils/testdata/ramus.rdf, apis_core/utils/testdata/ramus_gesellschaft.rdf, apis_core/utils/testdata/wien.rdf
=> fix(utils): use local files for rdf parser to circument http timeouts

apis_core/apis_entities/detail_generic.py, apis_core/apis_entities/edit_generic.py, apis_core/apis_entities/mixins.py
This commit introduces the EntityMixin and the EntityInstanceMixin which
can be used in views that handle entities. This way all those views have
access to the same class attributes.
=> feat: apis_entities: introduce apis_entities.mixins

apis_core/apis_entities/api_urls.py, apis_core/apis_entities/api_views.py, apis_core/apis_metainfo/viewsets.py, apis_core/urls.py
- feat(apis_metainfo): introduce an API endpoint for resolving URIs
- feat(apis_entities): remove legacy uri resolver
Closes: #167
=> Introduce new URI resolver and drop old one

.github/workflows/release-please.yml
This workflow keeps the changelog up to date and creates releases once
we want to release.
=> chore(workflows): introduce release-please workflow

pyproject.toml
=> chore: bump poetry version to 1.2.0

apis_core/apis_entities/detail_generic.py, apis_core/apis_entities/edit_generic.py, apis_core/utils/settings.py, docs/source/configuration.rst
- feat(utils): introduce APIS_ENTITIES function
- fix(apis_entities): make relations pagination configurable
- doc(apis_entites): document `relations_per_page` settings
Closes: #200
=> Introduce relation pagination

apis_core/apis_entities/models.py, apis_core/apis_metainfo/models.py, apis_core/apis_relations/models.py
- fix(apis_metainfo): register the rootobject with reversion
- fix(apis_entities): fix reversion for tempentity classes
- fix(apis_relations): fix follow of property reveversion registration
=> Fix reversion

apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html, apis_core/apis_entities/templates/apis_entities/edit_generic.html, apis_core/apis_metainfo/templates/apis_metainfo/uri_detail.html, apis_core/apis_metainfo/templates/base.html, apis_core/apis_metainfo/templates/partials/feather_js.html, apis_core/apis_relations/templates/apis_relations/delete_button_generic_ajax_form.html, apis_core/apis_relations/templates/apis_relations/edit_button_generic_ajax_form.html, apis_core/apis_relations/templates/apis_relations/references_button_generic_ajax_form.html
- removes logic for rendering feather icons
- adds link to material symbols stylesheet to base.html
- replaces all feather icons with material symbols
resolves #243
=> feat: replaces feather icons with material-symbols

apis_core/apis_metainfo/templates/base.html
This allows projects to add their own items to predefined submenus
Closes: #306
=> feat: put main-menu submenu items in separate blocks

apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html, apis_core/apis_entities/templates/apis_entities/edit_generic.html
This commit reduces borders around elements in the `General Info` table
in the detail view and in the edit form in the edit view.
=> feat: cleanup the default entity detail and edit view

apis_core/apis_entities/models.py
fixes #341
`merge_with` expected the class to be of instance TempEntityClass and use django-reversion. This fix checks if both really exist.
=> fix: fixes merge function to not expect TempEntityClass to be installed

apis_core/apis_metainfo/templates/base.html
This makes it easier to override
=> fix(ux): add nav class in template block

README.md
=> docs: rearrange installation info and add URL dispatcher info

apis_core/apis_entities/forms.py
Those are part of TempEntityClass which we don't require anymore to be
used.
Closes: #405
=> fix: don't expect entities to have {start|end}_date_written fields

.github/workflows/django-tests.yml, apis_core/apis_metainfo/test_models.py
=> ci: run tests also with Python 3.12

apis_core/apis_metainfo/templates/base.html, apis_core/core/templates/partials/backtotopbtn.html
=> refactor: replace external scrolltotop solution with own

.github/workflows/pages.yml
=> ci: fix documentation build

apis_core/apis_entities/templates/apis_entities/edit_generic.html
=> fix: link to delete view in entity edit template

apis_core/apis_entities/models.py
=> fix: checks if collections exist in merge func

apis_core/apis_entities/forms.py, apis_core/apis_entities/models.py, apis_core/apis_metainfo/models.py, apis_core/apis_relations/rel_filters.py, apis_core/utils/helpers.py
We remove unused imports, fix a variable name, and remove a search
filter function that was not being used anymore
=> chore: another ruff induces code cleanup

apis_core/generic/helpers.py
... this way it also picks the nth element if the first n-1 ones are
False
=> fix: filter the iterator before picking the first element

apis_core/generic/filtersets.py
The custom implementation did not allow to use custom Meta attributes
=> fix: backport `filterset_factory` from django-filters

apis_core/collections/templatetags/apis_collections.py
This templatetag allows to list collectionobjects an instance is
connected to.
=> fix(collections): add collection_content_objects templatetag

apis_core/default_settings/URI_replace_settings.yml, apis_core/utils/clean_uri.toml, apis_core/utils/normalize.py, apis_core/utils/settings.py
... and move the `clean_uri.toml` to the `utils` folder
Closes: #572
=> refactor(utils): replace URI_replace_settings.yml with clean_uri.toml

apis_core/generic/forms/__init__.py, apis_core/generic/forms/fields.py, apis_core/generic/importers.py, apis_core/generic/templates/generic/generic_import.html, apis_core/generic/urls.py, apis_core/generic/views.py, docs/source/importing.rst, docs/source/index.rst
=> feat: implement extendable autocomplete importer

apis_core/core/mixins.py, apis_core/generic/views.py
This lets us give access to the list view to anonymous users for
selected items
=> fix: use the ListViewObjectFilterMixin in the generic.views.List view

apis_core/generic/templates/generic/generic_detail.html, apis_core/generic/templates/generic/partials/object_card.html, apis_core/generic/templates/generic/partials/object_table.html
This way we can reuse the partials in other templates
=> refactor(generic): use partials for generic detail template

apis_core/generic/views.py
.. instead of redirecting to list view - another option would be detail
view, but in our usecases, the update view makes more sense
=> fix(generic): redirect to update view after create or update

apis_core/apis_entities/templates/apis_entities/partials/entity_actions_nav.html
This should be refactored at some point (maybe using a templatetag?)
=> fix(generic): check for permissions in actions nav

apis_core/utils/utils.py
This makes this function a lot easier to read
Closes: #582
=> fix(utils): refactor `access_for_all`

apis_core/utils/rdf.py
=> fix(utils): make rdf parser more robust

apis_core/apis_metainfo/models.py
This lets APIS provide generic views for the Collection model
=> fix(apis_metainfo): let Collection inherit from GenericModel

apis_core/apis_relations/filtersets.py
=> feat(apis_relations): add obj_class and subj_class filter to triple filterset

apis_core/apis_entities/tables.py
=> fix(apis_entities): move duplicate button after other action buttons

apis_core/core/templates/base.html
=> fix(core): remove hardcoded imprint pointing to 404

apis_core/apis_entities/templates/apis_core/apis_entities/abstractentity.html, apis_core/apis_entities/templates/apis_entities/partials/entity_actions_nav.html, apis_core/apis_entities/templates/apis_entities/partials/entity_base_nav.html
That way they can be overridden or extended
=> feat(apis_entities): surround navigation elements with block

apis_core/generic/forms/widgets.py, apis_core/generic/static/js/multiline.js, apis_core/generic/templates/widgets/multiline.html
Those widget provide a multiline input with a javascript based 'more'
button, that adds additional input elements.
Closes: #733
=> feat(generic): ship a JSON based and a newline based list widget

apis_core/generic/api_views.py, apis_core/generic/filterbackends.py
The GenericFilterBackend looks for a filter specific to the model with
the suffix `FilterSet` (which is the default suffix for the filters used
in the list view) or `ApiFilterSet`.
=> feat(generic): introduce GenericFilterBackend and use it

apis_core/apis_entities/tables.py, apis_core/generic/tables.py
This allows us to use the table without a model set and with records of
different models
=> fix(generic): move permission check to individual rows

apis_core/history/models.py, apis_core/history/views.py
=> fix(history): make history timezone aware

apis_core/utils/helpers.py
The `get_html_diff` helper provides an html representation of a change
in two values. It can be used to compare two objects and shows the
additions, removals or changes.
=> feat(utils): introduce `get_html_diff` helper

apis_core/core/templates/base.html
=> fix(core): use the capfirst filter on entity menu entries

apis_core/apis_entities/api_views.py
=> refactor(apis_entities): rewrite GetEntityGeneric

apis_core/apis_entities/api_views.py, apis_core/apis_entities/serializers.py, apis_core/apis_entities/utils.py, apis_core/urls.py
=> feat(apis_entities): add endpoint that lists all entities

apis_core/apis_entities/models.py
This cleans up the create_default_uri signal receiver - mainly to drop
the dependency on `caching`, but also to make it more readable.
=> refactor(apis_entities): rewrite create_default_uri

docs/source/history.rst
=> Fix formatting issues in history documentation

apis_core/apis_relations/forms.py, apis_core/apis_relations/views.py
That way we have access to the user object and can check the
permissions.
=> fix(apis_relations): pass the request to the table

.github/workflows/deploy.yml
That way we can trigger the run from the webinterface
=> fix(ci): replace workflow_call with workflow_dispatch

apis_core/apis_relations/tables.py
This commit move the TripleTableBase, TripleTableEdit and
TripleTableDetail out of the factory. It also moves up an import and
deletes some unnecessary comments. This is a further step in cleanin up
this whole tripletable mess.
=> refactor(apis_relations): cleanup triple table factory

apis_core/utils/fields.py
This field is based on the NewlineSeparatedListWidget. It makes it
possible to use the widget without having to set the widget in the form.
=> feat(utils): add a NewlineSeparatedListField

apis_core/apis_entities/api_views.py, apis_core/utils/filters.py
=> feat(apis_entities): introduce CustomSearchFilter and use it

.github/workflows/deploy.yml
=> fix(ci): add datetime tag to image

sample_project/templates/base.html, sample_project/templatetags/sample_project.py
=> fix(sample_project): show countdown until redeployment

docs/source/configuration.rst, docs/source/index.rst
=> fix(docs): add documentation regarding GetEntityGeneric

sample_project/templatetags/sample_project.py
=> fix(sample_project): fix countdown

apis_core/apis_metainfo/tables.py
... and replace `desc` with `uri` (making it also orderable)
Closes: #874
=> fix(apis_metainfo): make entity_type orderable in the UriTable

apis_core/apis_entities/views.py
=> feat(apis_entities): add info message to duplicated object

apis_core/apis_entities/templates/apis_core/apis_entities/abstractentity_detail.html, apis_core/apis_entities/templates/apis_core/apis_entities/abstractentity_form.html, apis_core/apis_entities/templates/apis_entities/partials/entity_actions_nav.html, apis_core/apis_entities/templates/apis_entities/partials/entity_base_nav.html, apis_core/apis_entities/templates/apis_entities/partials/entity_relations_multiple_cards.html, apis_core/apis_entities/templates/apis_entities/partials/linked_open_data.html, apis_core/apis_entities/templates/apis_entities/partials/listview_url.html, apis_core/apis_metainfo/templates/browsing/generic_create.html, apis_core/apis_metainfo/templates/generic_list.html, apis_core/apis_relations/templates/apis_relations/_ajax_form.html, apis_core/apis_relations/templates/apis_relations/_ajax_form_generic.html, apis_core/apis_relations/templates/apis_relations/references_button_generic_ajax_form.html, apis_core/apis_relations/templates/apis_relations/relations_detail_generic.html, apis_core/collections/templates/collections/collection_toggle.html, apis_core/core/templates/base.html, apis_core/generic/templates/generic/generic_detail.html, apis_core/generic/templates/generic/generic_form.html, apis_core/generic/templates/generic/generic_list.html, apis_core/history/templates/apis_core/history/apishistorytablebase_detail.html, apis_core/history/templates/history/columns/fields_changed.html, pyproject.toml, sample_project/templates/base.html
Those `blank_line_` statements make problems with inline statements.
Closes: #1001
=> chore(deps): update djlint customization regarding if and endif

apis_core/generic/importers.py
- refactor(generic)!: rename `GenericImporter` to `GenericModelImporter`
- feat(generic): add data received to importer error message
- feat(generic): let the importer try rdf before the json fallback
=> GenericImporter improvements

apis_core/apis_entities/filtersets.py, apis_core/generic/filtersets.py, apis_core/generic/forms/__init__.py, apis_core/generic/views.py
- **refactor(generic): move the column selector logic to the view**
- **feat(generic): fix and extend the columns selector**
- **fix(apis_entities): split excluded filters and excluded columns**
=> Refactor and enhance column selector

apis_core/generic/views.py
Include ManyToMany fields in 'additional columns' dropdown as well as in table.
Closes: #1020
=> fix(generic): include many-to-many relationships in list view

apis_core/apis_entities/filtersets.py
=> fix(apis_entities): remove inherited related fields from column list

apis_core/apis_entities/templates/apis_core/apis_entities/abstractentity_detail.html
Add linked_open_data partial to template for entity detail view for consistency with edit view.
Closes: #861
=> feat(apis_entities): add external Uris to detail view

apis_core/apis_entities/serializers.py, apis_core/history/serializers.py
- fix(apis_entities): set return type of serializer method
- fix(history): set return types of serialzers methods
=> Fix some DRF warnings

apis_core/apis_entities/filtersets.py
=> feat(apis_entities): add `changed since` filter to entity filterset

sample_project/querysets.py
=> fix(sample_project): add autocomplete querysets for person and place

pyproject.toml
Follow-on from https://github.com/acdh-oeaw/apis-core-rdf/pull/1054#issuecomment-2250736271.
=> build: update project author name

apis_core/apis_entities/filtersets.py
This default search uses `generic.helpers.generate_search_filter` to
either search through all the Char and Textfields or through the fields
the model has defined in `_default_search_fields`.
It uses the same logic to list the searched fields in the help text of
the searchfield.
=> feat(apis_entities): add a default search field to the entity filtersets

apis_core/history/tables.py
=> fix(history): change column name in table to a more accurate term

apis_core/apis_entities/views.py
=> fix(apis_entities): make autocomplete work with multilevel inheritance

sample_project/settings.py
fixes an issue where signal provided in PR #1074 doesnt trigger correctly
=> chore(sample_project): add crum middleware to settings

apis_core/generic/templatetags/apisgeneric.py
This templatetag provides a `getattr` like functionality
=> feat(generic): introduce a `get_attribute` templatetag

apis_core/generic/importers.py
This commit adds an intermediate `get_data` method to the Importer
class. This allows us to access the data without creating an object out
of it.
=> refactor(generic): add an intermediate step in the Importer logic

apis_core/core/static/css/core.css, apis_core/core/templates/base.html
Instead of simple divs, we now use the `header`, `main` and `footer`
semantic elements. The `imprint` block is now part of the `footer-right`
block.
=> refactor!(core): cleanup the base.html template

apis_core/relations/templates/apis_core/apis_entities/abstractentity_form.html
=> prevents choices being treated as autocomplete

apis_core/apis_entities/models.py
=> fix(merge-entities): use source obj's bool value

CONTRIBUTING.md
=> docs: update the CONTRIBUTING file

apis_core/relations/utils.py
=> fix(relations): disable cache on the relation_match_target function

apis_core/apis_entities/static/js/E53_Place_detail_map.js, apis_core/apis_entities/templates/apis_core/apis_entities/e53_place_detail.html
=> feat(apis_entities): introduce a map view for E53_Place entities

apis_core/generic/abc.py, apis_core/generic/templates/generic/generic_list.html
=> feat(generic): add an import button to the list views

docs/source/development.rst, docs/source/index.rst
The development chapter was accidently removed in
5b107cc08732ca78c6ea2f55e126f3c2b23f2706
=> docs: readd the development chapter, that was accidently removed

apis_core/core/templatetags/core.py
=> fix(core): use a generic setting instead of an environment variable

apis_core/core/static/css/core.css, apis_core/core/static/css/material-symbols.css
Move CSS for Material Symbols to appropriate file, add, clean up comments, formatting in CSS files.
=> refactor(core): clean up static files

apis_core/core/models.py
=> feat(core): allow to skip dateparsing in LegacyDateMixin

sample_project/settings.py
=> feat(sample_project): enable debug logging

apis_core/apis_relations/templates/apis_relations/edit_button_generic_ajax_form.html
Style edit button in relations tables consistent
with edit button in list view (colour, title).
=> fix(apis_relations): edit button appearance

sample_project/entrypoint.sh
=> feat(sample_project): automaticall add admin

apis_core/generic/abc.py
This method lets us print more meaningful debug messages without having
to add the ID to the str dunder method.
=> feat(generic): add a repr dunder method to the GenericModel

apis_core/relations/apps.py, apis_core/relations/signals.py
=> feat(relations): implement duplicate and merge signal receivers

apis_core/core/templates/base.html, apis_core/core/templates/partials/bootstrap4_css.html
=> refactor(core): include stylesheet directly instead of using partial

apis_core/core/templates/base.html, apis_core/core/templates/partials/bootstrap4_js.html
=> refactor(core): include script tag directly instead of using partial

apis_core/apis_entities/forms.py, apis_core/apis_relations/forms.py, apis_core/generic/forms/__init__.py, apis_core/generic/views.py, apis_core/relations/forms.py
- **fix(generic): use a URL param to enable autocomplete create function**
- **feat(generic): allow to paste a string in the import form**
=> Adapt autocomplete configuration

.github/workflows/django-migrations.yml
=> ci: add workflow to check if there are missing migrations

CHANGELOG.md
=> docs(changelog): replace wrong bug number with correct one

apis_core/core/templates/base.html
This allows to add additional items to the user-menu
=> feat(core): enclose user-menu items in a block

docs/source/features.rst
=> docs(features): fix typo

apis_core/generic/filtersets.py
=> fix(generic): set unknown_field_behavior to WARN in GenericFilterSet

apis_core/core/templates/base.html
=> feat(core): update htmx script inclusion to v2.0.4

apis_core/generic/templates/base.html
=> fix(generic): use verbose_name_plural for generic menu items

sample_project/fixtures/sample_project.json
=> fix(sample_project): drop self_contenttype from fixtures

apis_core/apis_entities/models.py, apis_core/core/models.py
=> refactor(apis_entities): move merge methods to LegacyDateMixin

apis_core/apis_entities/views.py
The `get_queryset` method of the view ignored the query if the request
did not pass any entity types as request parameters. Given that we also
want to be able to use this autocomplete view without passing specific
entities, but simply search over **all** entity types, we now check if
there are entities passed in the `entities` get request parameter and
otherwise we use the list of all entities.
=> fix(apis_entities): fix entities autocomplete

apis_core/generic/templates/generic/generic_list.html
=> fix(generic): show form errors of generic filter form

apis_core/utils/rdf.py
=> fix(utils): allow to pass an URI string to rdf config filter

apis_core/apis_entities/abc.py
The SimpleLabelModel provides an abstract model that only has a label
and comes with the most useful methods.
Closes: #1686
=> feat(apis_entities): ship SimpleLabelModel

apis_core/relations/abc.py
=> feat(relations): ship some default relations

apis_core/relations/forms/__init__.py
... and set subj and obj object_id
Closes: #1712
=> fix(relations): work around initial data being empty

apis_core/generic/importers.py, apis_core/utils/rdf.py
=> fix: tunnel models through importer chain

apis_core/generic/templates/generic/generic_confirm_delete.html
=> fix(generic): put `extends` at beginning of template

apis_core/documentation/locale/de/LC_MESSAGES/django.po, apis_core/documentation/templates/base.html
=> feat(documentation): add menu entry for the documentation app

apis_core/generic/static/css/generic.css
=> fix(generic): make the object-action css classes important

apis_core/apis_entities/models.py, apis_core/relations/models.py
not sure this is the right way to do it, but this fixed the issue
in the OEBL instance for institutions.
resolves #1655
=> fix: remove duplicate entries in API

apis_core/relations/forms/fields.py
=> fix(relations): make RelationMultiWidget not use a fieldset

apis_core/apis_entities/templates/apis_entities/partials/linked_open_data.html
=> fix(apis_entities): add a to the bottom of the pills in the lod block

apis_core/generic/importers.py
Fix grammar, spelling, punctuation; add paragraphs to docstrings, make first line a (useful) summary
line following PEP 257 recommendation.
=> docs(generic): update importers docstrings, comments

apis_core/apis_entities/serializers.py
=> feat(apis_entities): introduce E53_PlaceCidocSerializer

apis_core/relations/models.py
=> fix(relations): only check for subj & obj in concrete subclasses

.github/workflows/django-tests.yml
=> ci(django-tests): check openapi schema generation as part of testing

sample_project/settings.py
This way its possible to use the sample project in other languages
Closes: #1867
=> feat(sample_project): add LocaleMiddleware to the list of middlewares

apis_core/utils/autocomplete.py, pyproject.toml
This only affects the autocomplete code
Closes: #1040
=> feat(deps): replace `requests` with `httpx`

apis_core/relations/forms/__init__.py, apis_core/relations/locale/de/LC_MESSAGES/django.po
Replace the rather complicated relation form, that implemented to work
with Relations with multiple subj or obj types, which a much simpler
form that only works with Relations that have one subj or obj type.
=> feat(relations): refactor the whole relations form

apis_core/relations/filtersets.py
=> fix(relations): remove collections filter from relations filterset

apis_core/collections/columns.py, apis_core/collections/forms.py, apis_core/collections/locale/de/LC_MESSAGES/django.po, apis_core/collections/templates/collections/collection_object_form.html, apis_core/collections/templates/collections/columns/collections.html, apis_core/collections/urls.py, apis_core/collections/views.py, apis_core/history/tables.py
and add a link to the history table to be able to add histories to collections
Closes: #1901
=> feat: allow adding objects to collections

apis_core/generic/locale/de/LC_MESSAGES/django.po, apis_core/generic/templates/generic/genericmodel_duplicate_success_message.html, apis_core/generic/views.py
... and translate the string
Closes: #2003
=> feat(generic): use template lookup instead of hardcoding duplicate msg

apis_core/core/templates/base.html
=> fix(core): move remainig script tags to header & use defer

apis_core/apis_entities/models.py, apis_core/apis_metainfo/signals.py
=> feat(apis_metainfo): move signal receiver to correct app

apis_core/apis_metainfo/signals.py, apis_core/generic/abc.py
... and drop the code that does this in the GenericModel mixin
Closes: #2005
=> feat(apis_metainfo): introduce signal to retarget Uris on merge

sample_project/querysets.py
=> feat(sample_project): add autocomplete queryset for Group

apis_core/apis_entities/featureCodes_en.txt, apis_core/apis_entities/forms.py, apis_core/apis_entities/utils.py
=> feat(apis_entities): add and use a featurecodes class

apis_core/apis_entities/fields.py, apis_core/apis_entities/static/js/placelookup.js, apis_core/apis_entities/templates/apis_entities/widgets/placelookup.html
... and allow to select *any* place using left click
Closes: #2068
=> feat(apis_entities): extend place lookup to show existing values

apis_core/utils/rdf.py
- **feat(utils): allow to pass a config to `get_something_from_uri`**
- **fix(utils): only copy the attribute if it really exists**
=> small rdf improvements
